# Base16 Gruvbox Light - wezterm color config
# Scheme by Tinted Theming (https://github.com/tinted-theming), morhetz (https://github.com/morhetz/gruvbox)
[colors]
background = "#fbf1c7"
foreground = "#3c3836"

cursor_bg = "#ebdbb2"
cursor_border = "#3c3836"
cursor_fg = "#282828"

selection_bg = "#3c3836"
selection_fg = "#fbf1c7"

ansi = [
  "#fbf1c7",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#282828"
  ]
brights = [
  "#bdae93",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#1d2021"
  ]

[colors.indexed]
16 = "#d65d0e"
17 = "#9d0006"
18 = "#ebdbb2"
19 = "#d5c4a1"
20 = "#7c6f64"
21 = "#3c3836"
