# Base16 Chalk - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#151515"
foreground = "#d0d0d0"

cursor_bg = "#202020"
cursor_border = "#d0d0d0"
cursor_fg = "#e0e0e0"

selection_bg = "#d0d0d0"
selection_fg = "#151515"

ansi = [
  "#151515",
  "#fb9fb1",
  "#acc267",
  "#ddb26f",
  "#6fc2ef",
  "#e1a3ee",
  "#12cfc0",
  "#e0e0e0"
  ]
brights = [
  "#505050",
  "#fb9fb1",
  "#acc267",
  "#ddb26f",
  "#6fc2ef",
  "#e1a3ee",
  "#12cfc0",
  "#f5f5f5"
  ]

[colors.indexed]
16 = "#eda987"
17 = "#deaf8f"
18 = "#202020"
19 = "#303030"
20 = "#b0b0b0"
21 = "#d0d0d0"
