# Base16 Atelier Cave Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#efecf4"
foreground = "#585260"

cursor_bg = "#585260"
cursor_border = "#585260"
cursor_fg = "#efecf4"

selection_bg = "#585260"
selection_fg = "#efecf4"

ansi = [
  "#efecf4",
  "#be4678",
  "#2a9292",
  "#a06e3b",
  "#576ddb",
  "#955ae7",
  "#398bc6",
  "#26232a"
  ]
brights = [
  "#7e7887",
  "#be4678",
  "#2a9292",
  "#a06e3b",
  "#576ddb",
  "#955ae7",
  "#398bc6",
  "#19171c"
  ]

[colors.indexed]
16 = "#aa573c"
17 = "#bf40bf"
18 = "#e2dfe7"
19 = "#8b8792"
20 = "#655f6d"
21 = "#585260"
