# base16 Praha
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#1a1a1a"
foreground = "#ffffff"

cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#1a1a1a"

selection_bg = "#ffffff"
selection_fg = "#353535"

ansi = [
  "#1a1a1a",
  "#ff5555",
  "#b8e6a0",
  "#ffe4a3",
  "#bd93f9",
  "#ff9aa2",
  "#8be9fd",
  "#ffffff"
]
brights = [
  "#6272a4",
  "#ff5555",
  "#b8e6a0",
  "#ffe4a3",
  "#bd93f9",
  "#ff9aa2",
  "#8be9fd",
  "#ffffff"
]

[colors.indexed]
16 = "#ff9c7c"
17 = "#af6e5a"
18 = "#2a2a2a"
19 = "#353535"
20 = "#989898"
21 = "#ffffff"
