# Base16 Da One Paper - wezterm color config
# Scheme by NNB (https://github.com/NNBnh)
[colors]
background = "#faf0dc"
foreground = "#181818"

cursor_bg = "#181818"
cursor_border = "#181818"
cursor_fg = "#faf0dc"

selection_bg = "#181818"
selection_fg = "#faf0dc"

ansi = [
  "#faf0dc",
  "#de5d6e",
  "#76a85d",
  "#b3684f",
  "#5890f8",
  "#c173d1",
  "#64b5a7",
  "#000000"
  ]
brights = [
  "#585858",
  "#de5d6e",
  "#76a85d",
  "#b3684f",
  "#5890f8",
  "#c173d1",
  "#64b5a7",
  "#000000"
  ]
