# Base16 PaperColor Light - wezterm color config
# Scheme by Jon Leopard (http://github.com/jonleopard), based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)
[colors]
background = "#eeeeee"
foreground = "#444444"

cursor_bg = "#af0000"
cursor_border = "#444444"
cursor_fg = "#005f87"

selection_bg = "#444444"
selection_fg = "#eeeeee"

ansi = [
  "#eeeeee",
  "#bcbcbc",
  "#8700af",
  "#d70087",
  "#d75f00",
  "#005faf",
  "#d75f00",
  "#005f87"
  ]
brights = [
  "#5f8700",
  "#bcbcbc",
  "#8700af",
  "#d70087",
  "#d75f00",
  "#005faf",
  "#d75f00",
  "#878787"
  ]

[colors.indexed]
16 = "#d70000"
17 = "#005f87"
18 = "#af0000"
19 = "#008700"
20 = "#0087af"
21 = "#444444"
