# Base16 London Tube - wezterm color config
# Scheme by Jan T. Sott
[colors]
background = "#231f20"
foreground = "#d9d8d8"

cursor_bg = "#d9d8d8"
cursor_border = "#d9d8d8"
cursor_fg = "#231f20"

selection_bg = "#d9d8d8"
selection_fg = "#231f20"

ansi = [
  "#231f20",
  "#ee2e24",
  "#00853e",
  "#ffd204",
  "#009ddc",
  "#98005d",
  "#85cebc",
  "#e7e7e8"
  ]
brights = [
  "#737171",
  "#ee2e24",
  "#00853e",
  "#ffd204",
  "#009ddc",
  "#98005d",
  "#85cebc",
  "#ffffff"
  ]
