# base24 Madrid
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#fafafa"
foreground = "#1a1a1a"

cursor_bg = "#1a1a1a"
cursor_border = "#1a1a1a"
cursor_fg = "#fafafa"

selection_bg = "#1a1a1a"
selection_fg = "#dfdfdf"

ansi = [
  "#fafafa",
  "#990026",
  "#007a28",
  "#8a6408",
  "#007a9e",
  "#4d2699",
  "#007a9e",
  "#1a1a1a"
]
brights = [
  "#4d4d4d",
  "#990026",
  "#007a28",
  "#8a6408",
  "#007a9e",
  "#4d2699",
  "#007a9e",
  "#1a1a1a"
]

[colors.indexed]
16 = "#923217"
17 = "#662310"
18 = "#eaeaea"
19 = "#dfdfdf"
20 = "#686868"
21 = "#121212"
