# Base16 Atelier Lakeside Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#ebf8ff"
foreground = "#516d7b"

cursor_bg = "#c1e4f6"
cursor_border = "#516d7b"
cursor_fg = "#1f292e"

selection_bg = "#516d7b"
selection_fg = "#ebf8ff"

ansi = [
  "#ebf8ff",
  "#d22d72",
  "#568c3b",
  "#8a8a0f",
  "#257fad",
  "#6b6bb8",
  "#2d8f6f",
  "#1f292e"
  ]
brights = [
  "#7195a8",
  "#d22d72",
  "#568c3b",
  "#8a8a0f",
  "#257fad",
  "#6b6bb8",
  "#2d8f6f",
  "#161b1d"
  ]

[colors.indexed]
16 = "#935c25"
17 = "#b72dd2"
18 = "#c1e4f6"
19 = "#7ea2b4"
20 = "#5a7b8c"
21 = "#516d7b"
