# Base16 Atelier Savanna Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#ecf4ee"
foreground = "#526057"

cursor_bg = "#526057"
cursor_border = "#526057"
cursor_fg = "#ecf4ee"

selection_bg = "#526057"
selection_fg = "#ecf4ee"

ansi = [
  "#ecf4ee",
  "#b16139",
  "#489963",
  "#a07e3b",
  "#478c90",
  "#55859b",
  "#1c9aa0",
  "#232a25"
  ]
brights = [
  "#78877d",
  "#b16139",
  "#489963",
  "#a07e3b",
  "#478c90",
  "#55859b",
  "#1c9aa0",
  "#171c19"
  ]

[colors.indexed]
16 = "#9f713c"
17 = "#867469"
18 = "#dfe7e2"
19 = "#87928a"
20 = "#5f6d64"
21 = "#526057"
