# Base16 Da One White - wezterm color config
# Scheme by NNB (https://github.com/NNBnh)
[colors]
background = "#ffffff"
foreground = "#181818"

cursor_bg = "#c8c8c8"
cursor_border = "#181818"
cursor_fg = "#000000"

selection_bg = "#181818"
selection_fg = "#ffffff"

ansi = [
  "#ffffff",
  "#de5d6e",
  "#76a85d",
  "#b3684f",
  "#5890f8",
  "#c173d1",
  "#64b5a7",
  "#000000"
  ]
brights = [
  "#585858",
  "#de5d6e",
  "#76a85d",
  "#b3684f",
  "#5890f8",
  "#c173d1",
  "#64b5a7",
  "#000000"
  ]
