# Base16 Tokyo Night Terminal Storm - wezterm color config
# Scheme by Michaël Ball
[colors]
background = "#24283b"
foreground = "#787c99"

cursor_bg = "#1a1b26"
cursor_border = "#787c99"
cursor_fg = "#cbccd1"

selection_bg = "#787c99"
selection_fg = "#24283b"

ansi = [
  "#24283b",
  "#f7768e",
  "#41a6b5",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#cbccd1"
  ]
brights = [
  "#444b6a",
  "#f7768e",
  "#41a6b5",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#d5d6db"
  ]
