# Base16 Black Metal (Dark Funeral) - wezterm color config
# Scheme by metalelf0 (https://github.com/metalelf0)
[colors]
background = "#000000"
foreground = "#c1c1c1"

cursor_bg = "#121212"
cursor_border = "#c1c1c1"
cursor_fg = "#999999"

selection_bg = "#c1c1c1"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#5f8787",
  "#d0dfee",
  "#5f81a5",
  "#888888",
  "#999999",
  "#aaaaaa",
  "#999999"
  ]
brights = [
  "#333333",
  "#5f8787",
  "#d0dfee",
  "#5f81a5",
  "#888888",
  "#999999",
  "#aaaaaa",
  "#c1c1c1"
  ]
