# Base16 Everforest Dark Hard - wezterm color config
# Scheme by Sainnhe Park (https://github.com/sainnhe)
[colors]
background = "#272e33"
foreground = "#d3c6aa"

cursor_bg = "#2e383c"
cursor_border = "#d3c6aa"
cursor_fg = "#edeada"

selection_bg = "#d3c6aa"
selection_fg = "#272e33"

ansi = [
  "#272e33",
  "#e67e80",
  "#a7c080",
  "#dbbc7f",
  "#7fbbb3",
  "#d699b6",
  "#83c092",
  "#edeada"
  ]
brights = [
  "#859289",
  "#e67e80",
  "#a7c080",
  "#dbbc7f",
  "#7fbbb3",
  "#d699b6",
  "#83c092",
  "#fffbef"
  ]
