# Base16 Atelier Heath - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#1b181b"
foreground = "#ab9bab"

cursor_bg = "#292329"
cursor_border = "#ab9bab"
cursor_fg = "#d8cad8"

selection_bg = "#ab9bab"
selection_fg = "#1b181b"

ansi = [
  "#1b181b",
  "#ca402b",
  "#918b3b",
  "#bb8a35",
  "#516aec",
  "#7b59c0",
  "#159393",
  "#d8cad8"
  ]
brights = [
  "#776977",
  "#ca402b",
  "#918b3b",
  "#bb8a35",
  "#516aec",
  "#7b59c0",
  "#159393",
  "#f7f3f7"
  ]

[colors.indexed]
16 = "#a65926"
17 = "#cc33cc"
18 = "#292329"
19 = "#695d69"
20 = "#9e8f9e"
21 = "#ab9bab"
