# Base16 Atelier Lakeside Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#ebf8ff"
foreground = "#516d7b"

cursor_bg = "#516d7b"
cursor_border = "#516d7b"
cursor_fg = "#ebf8ff"

selection_bg = "#516d7b"
selection_fg = "#ebf8ff"

ansi = [
  "#ebf8ff",
  "#d22d72",
  "#568c3b",
  "#8a8a0f",
  "#257fad",
  "#6b6bb8",
  "#2d8f6f",
  "#1f292e"
  ]
brights = [
  "#7195a8",
  "#d22d72",
  "#568c3b",
  "#8a8a0f",
  "#257fad",
  "#6b6bb8",
  "#2d8f6f",
  "#161b1d"
  ]
