# Base16 Kanagawa - wezterm color config
# Scheme by Tommaso Laurenzi (https://github.com/rebelot)
[colors]
background = "#1f1f28"
foreground = "#dcd7ba"

cursor_bg = "#16161d"
cursor_border = "#dcd7ba"
cursor_fg = "#c8c093"

selection_bg = "#dcd7ba"
selection_fg = "#1f1f28"

ansi = [
  "#1f1f28",
  "#c34043",
  "#76946a",
  "#c0a36e",
  "#7e9cd8",
  "#957fb8",
  "#6a9589",
  "#c8c093"
  ]
brights = [
  "#54546d",
  "#c34043",
  "#76946a",
  "#c0a36e",
  "#7e9cd8",
  "#957fb8",
  "#6a9589",
  "#717c7c"
  ]
