# Base16 Sakura - wezterm color config
# Scheme by Misterio77 (http://github.com/Misterio77)
[colors]
background = "#feedf3"
foreground = "#564448"

cursor_bg = "#f8e2e7"
cursor_border = "#564448"
cursor_fg = "#42383a"

selection_bg = "#564448"
selection_fg = "#feedf3"

ansi = [
  "#feedf3",
  "#df2d52",
  "#2e916d",
  "#c29461",
  "#006e93",
  "#5e2180",
  "#1d8991",
  "#42383a"
  ]
brights = [
  "#755f64",
  "#df2d52",
  "#2e916d",
  "#c29461",
  "#006e93",
  "#5e2180",
  "#1d8991",
  "#33292b"
  ]
