# Base16 Mocha - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#3b3228"
foreground = "#d0c8c6"

cursor_bg = "#534636"
cursor_border = "#d0c8c6"
cursor_fg = "#e9e1dd"

selection_bg = "#d0c8c6"
selection_fg = "#3b3228"

ansi = [
  "#3b3228",
  "#cb6077",
  "#beb55b",
  "#f4bc87",
  "#8ab3b5",
  "#a89bb9",
  "#7bbda4",
  "#e9e1dd"
  ]
brights = [
  "#7e705a",
  "#cb6077",
  "#beb55b",
  "#f4bc87",
  "#8ab3b5",
  "#a89bb9",
  "#7bbda4",
  "#f5eeeb"
  ]
