# Base16 Hopscotch - wezterm color config
# Scheme by Jan T. Sott
[colors]
background = "#322931"
foreground = "#b9b5b8"

cursor_bg = "#b9b5b8"
cursor_border = "#b9b5b8"
cursor_fg = "#322931"

selection_bg = "#b9b5b8"
selection_fg = "#322931"

ansi = [
  "#322931",
  "#dd464c",
  "#8fc13e",
  "#fdcc59",
  "#1290bf",
  "#c85e7c",
  "#149b93",
  "#d5d3d5"
  ]
brights = [
  "#797379",
  "#dd464c",
  "#8fc13e",
  "#fdcc59",
  "#1290bf",
  "#c85e7c",
  "#149b93",
  "#ffffff"
  ]
