# Base16 Gruvbox Material Light, Soft - wezterm color config
# Scheme by Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
[colors]
background = "#f2e5bc"
foreground = "#654735"

cursor_bg = "#654735"
cursor_border = "#654735"
cursor_fg = "#f2e5bc"

selection_bg = "#654735"
selection_fg = "#f2e5bc"

ansi = [
  "#f2e5bc",
  "#c14a4a",
  "#6c782e",
  "#b47109",
  "#45707a",
  "#945e80",
  "#4c7a5d",
  "#3c3836"
  ]
brights = [
  "#a89984",
  "#c14a4a",
  "#6c782e",
  "#b47109",
  "#45707a",
  "#945e80",
  "#4c7a5d",
  "#282828"
  ]
