# Base16 Mellow Purple - wezterm color config
# Scheme by gidsi
[colors]
background = "#1e0528"
foreground = "#ffeeff"

cursor_bg = "#ffeeff"
cursor_border = "#ffeeff"
cursor_fg = "#1e0528"

selection_bg = "#ffeeff"
selection_fg = "#1e0528"

ansi = [
  "#1e0528",
  "#00d9e9",
  "#05cb0d",
  "#955ae7",
  "#550068",
  "#8991bb",
  "#b900b1",
  "#ffeeff"
  ]
brights = [
  "#320f55",
  "#00d9e9",
  "#05cb0d",
  "#955ae7",
  "#550068",
  "#8991bb",
  "#b900b1",
  "#f8c0ff"
  ]

[colors.indexed]
16 = "#aa00a3"
17 = "#4d6fff"
18 = "#1a092d"
19 = "#331354"
20 = "#873582"
21 = "#ffeeff"
