# Base16 Equilibrium Gray Dark - wezterm color config
# Scheme by Carlo Abelli
[colors]
background = "#111111"
foreground = "#ababab"

cursor_bg = "#ababab"
cursor_border = "#ababab"
cursor_fg = "#111111"

selection_bg = "#ababab"
selection_fg = "#111111"

ansi = [
  "#111111",
  "#f04339",
  "#7f8b00",
  "#bb8801",
  "#008dd1",
  "#6a7fd2",
  "#00948b",
  "#c6c6c6"
  ]
brights = [
  "#777777",
  "#f04339",
  "#7f8b00",
  "#bb8801",
  "#008dd1",
  "#6a7fd2",
  "#00948b",
  "#e2e2e2"
  ]
