# base16 Sequoia Moonlight Light
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#edeef2"
foreground = "#282930"

cursor_bg = "#282930"
cursor_border = "#282930"
cursor_fg = "#edeef2"

selection_bg = "#282930"
selection_fg = "#e2e3e8"

ansi = [
  "#edeef2",
  "#c94da8",
  "#4a85d4",
  "#6a6a78",
  "#9a5fd9",
  "#6a6a78",
  "#d9884a",
  "#282930"
]
brights = [
  "#565760",
  "#c94da8",
  "#4a85d4",
  "#6a6a78",
  "#9a5fd9",
  "#6a6a78",
  "#d9884a",
  "#0f1014"
]

[colors.indexed]
16 = "#c94da8"
17 = "#4a85d4"
18 = "#e2e3e8"
19 = "#e2e3e8"
20 = "#42434e"
21 = "#282930"
