# base16 Tomorrow
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#ffffff"
foreground = "#4d4d4c"

cursor_bg = "#4d4d4c"
cursor_border = "#4d4d4c"
cursor_fg = "#ffffff"

selection_bg = "#4d4d4c"
selection_fg = "#d6d6d6"

ansi = [
  "#ffffff",
  "#c82829",
  "#718c00",
  "#eab700",
  "#4271ae",
  "#8959a8",
  "#3e999f",
  "#282a2e"
]
brights = [
  "#d6d6d6",
  "#c82829",
  "#718c00",
  "#eab700",
  "#4271ae",
  "#8959a8",
  "#3e999f",
  "#1d1f21"
]

[colors.indexed]
16 = "#f5871f"
17 = "#a3685a"
18 = "#e0e0e0"
19 = "#d6d6d6"
20 = "#969896"
21 = "#4d4d4c"
