# Base16 Gruvbox Material Light, Hard - wezterm color config
# Scheme by Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
[colors]
background = "#f9f5d7"
foreground = "#654735"

cursor_bg = "#fbf1c7"
cursor_border = "#654735"
cursor_fg = "#3c3836"

selection_bg = "#654735"
selection_fg = "#f9f5d7"

ansi = [
  "#f9f5d7",
  "#c14a4a",
  "#6c782e",
  "#b47109",
  "#45707a",
  "#945e80",
  "#4c7a5d",
  "#3c3836"
  ]
brights = [
  "#a89984",
  "#c14a4a",
  "#6c782e",
  "#b47109",
  "#45707a",
  "#945e80",
  "#4c7a5d",
  "#282828"
  ]

[colors.indexed]
16 = "#c35e0a"
17 = "#e78a4e"
18 = "#fbf1c7"
19 = "#e0cfa9"
20 = "#c9b99a"
21 = "#654735"
