# Base16 Sandcastle - wezterm color config
# Scheme by George Essig (https://github.com/gessig)
[colors]
background = "#282c34"
foreground = "#a89984"

cursor_bg = "#a89984"
cursor_border = "#a89984"
cursor_fg = "#282c34"

selection_bg = "#a89984"
selection_fg = "#282c34"

ansi = [
  "#282c34",
  "#83a598",
  "#528b8b",
  "#a07e3b",
  "#83a598",
  "#d75f5f",
  "#83a598",
  "#d5c4a1"
  ]
brights = [
  "#665c54",
  "#83a598",
  "#528b8b",
  "#a07e3b",
  "#83a598",
  "#d75f5f",
  "#83a598",
  "#fdf4c1"
  ]
