# Base16 Stella - wezterm color config
# Scheme by Shrimpram
[colors]
background = "#2b213c"
foreground = "#998bad"

cursor_bg = "#362b48"
cursor_border = "#998bad"
cursor_fg = "#b4a5c8"

selection_bg = "#998bad"
selection_fg = "#2b213c"

ansi = [
  "#2b213c",
  "#c79987",
  "#acc79b",
  "#c7c691",
  "#a5aad4",
  "#c594ff",
  "#9bc7bf",
  "#b4a5c8"
  ]
brights = [
  "#655978",
  "#c79987",
  "#acc79b",
  "#c7c691",
  "#a5aad4",
  "#c594ff",
  "#9bc7bf",
  "#ebdcff"
  ]

[colors.indexed]
16 = "#8865c6"
17 = "#c7ab87"
18 = "#362b48"
19 = "#4d4160"
20 = "#7f7192"
21 = "#998bad"
