# Base16 SAGA - wezterm color config
# Scheme by https://github.com/SAGAtheme/SAGA
[colors]
background = "#05080a"
foreground = "#dce2f7"

cursor_bg = "#dce2f7"
cursor_border = "#dce2f7"
cursor_fg = "#05080a"

selection_bg = "#dce2f7"
selection_fg = "#05080a"

ansi = [
  "#05080a",
  "#ffd4e9",
  "#f7ddff",
  "#fbebc8",
  "#c9fff7",
  "#dcc3f9",
  "#c5edc1",
  "#f8eae7"
  ]
brights = [
  "#141f27",
  "#ffd4e9",
  "#f7ddff",
  "#fbebc8",
  "#c9fff7",
  "#dcc3f9",
  "#c5edc1",
  "#ccd3fe"
  ]

[colors.indexed]
16 = "#fbcbae"
17 = "#f6dddd"
18 = "#0a1014"
19 = "#0f181e"
20 = "#192630"
21 = "#dce2f7"
