# Base16 Horizon Terminal Dark - wezterm color config
# Scheme by Michaël Ball (http://github.com/michael-ball/)
[colors]
background = "#1c1e26"
foreground = "#cbced0"

cursor_bg = "#232530"
cursor_border = "#cbced0"
cursor_fg = "#dcdfe4"

selection_bg = "#cbced0"
selection_fg = "#1c1e26"

ansi = [
  "#1c1e26",
  "#e95678",
  "#29d398",
  "#fac29a",
  "#26bbd9",
  "#ee64ac",
  "#59e1e3",
  "#dcdfe4"
  ]
brights = [
  "#6f6f70",
  "#e95678",
  "#29d398",
  "#fac29a",
  "#26bbd9",
  "#ee64ac",
  "#59e1e3",
  "#e3e6ee"
  ]
