# Base16 Deep Oceanic Next - wezterm color config
# Scheme by spearkkk (https://github.com/spearkkk)
[colors]
background = "#001c1f"
foreground = "#d4e1e8"

cursor_bg = "#d4e1e8"
cursor_border = "#d4e1e8"
cursor_fg = "#001c1f"

selection_bg = "#d4e1e8"
selection_fg = "#001c1f"

ansi = [
  "#001c1f",
  "#d3464d",
  "#63b784",
  "#f3b863",
  "#568ccf",
  "#8b66d6",
  "#4fb7ae",
  "#e0e9ef"
  ]
brights = [
  "#004852",
  "#d3464d",
  "#63b784",
  "#f3b863",
  "#568ccf",
  "#8b66d6",
  "#4fb7ae",
  "#f2f7f9"
  ]
