# Base16 Tokyo Night Moon - wezterm color config
# Scheme by Ólafur Bjarki Bogason
[colors]
background = "#222436"
foreground = "#3b4261"

cursor_bg = "#1e2030"
cursor_border = "#3b4261"
cursor_fg = "#828bb8"

selection_bg = "#3b4261"
selection_fg = "#222436"

ansi = [
  "#222436",
  "#ff757f",
  "#c3e88d",
  "#ffc777",
  "#82aaff",
  "#fca7ea",
  "#86e1fc",
  "#828bb8"
  ]
brights = [
  "#636da6",
  "#ff757f",
  "#c3e88d",
  "#ffc777",
  "#82aaff",
  "#fca7ea",
  "#86e1fc",
  "#c8d3f5"
  ]

[colors.indexed]
16 = "#ffc777"
17 = "#c53b53"
18 = "#1e2030"
19 = "#2d3f76"
20 = "#828bb8"
21 = "#3b4261"
