# Base16 Codeschool - wezterm color config
# Scheme by blockloop
[colors]
background = "#232c31"
foreground = "#9ea7a6"

cursor_bg = "#9ea7a6"
cursor_border = "#9ea7a6"
cursor_fg = "#232c31"

selection_bg = "#9ea7a6"
selection_fg = "#232c31"

ansi = [
  "#232c31",
  "#2a5491",
  "#237986",
  "#a03b1e",
  "#484d79",
  "#c59820",
  "#b02f30",
  "#a7cfa3"
  ]
brights = [
  "#3f4944",
  "#2a5491",
  "#237986",
  "#a03b1e",
  "#484d79",
  "#c59820",
  "#b02f30",
  "#b5d8f6"
  ]
