# Base16 Da One Gray - wezterm color config
# Scheme by NNB (https://github.com/NNBnh)
[colors]
background = "#181818"
foreground = "#ffffff"

cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#181818"

selection_bg = "#ffffff"
selection_fg = "#181818"

ansi = [
  "#181818",
  "#fa7883",
  "#98c379",
  "#ff9470",
  "#6bb8ff",
  "#e799ff",
  "#8af5ff",
  "#ffffff"
  ]
brights = [
  "#888888",
  "#fa7883",
  "#98c379",
  "#ff9470",
  "#6bb8ff",
  "#e799ff",
  "#8af5ff",
  "#ffffff"
  ]
