# Base16 Blue Forest - wezterm color config
# Scheme by alonsodomin (https://github.com/alonsodomin)
[colors]
background = "#141f2e"
foreground = "#ffcc33"

cursor_bg = "#1e5c1e"
cursor_border = "#ffcc33"
cursor_fg = "#91ccff"

selection_bg = "#ffcc33"
selection_fg = "#141f2e"

ansi = [
  "#141f2e",
  "#fffab1",
  "#80ff80",
  "#91ccff",
  "#a2cff5",
  "#0099ff",
  "#80ff80",
  "#91ccff"
  ]
brights = [
  "#a0ffa0",
  "#fffab1",
  "#80ff80",
  "#91ccff",
  "#a2cff5",
  "#0099ff",
  "#80ff80",
  "#375780"
  ]
