# Base16 0x96f - wezterm color config
# Scheme by Filip Janevski (https://0x96f.dev/theme)
[colors]
background = "#262427"
foreground = "#fcfcfc"

cursor_bg = "#fcfcfc"
cursor_border = "#fcfcfc"
cursor_fg = "#262427"

selection_bg = "#fcfcfc"
selection_fg = "#262427"

ansi = [
  "#262427",
  "#ff7272",
  "#bcdf59",
  "#ffca58",
  "#49cae4",
  "#a093e2",
  "#aee8f4",
  "#eae9eb"
  ]
brights = [
  "#676567",
  "#ff7272",
  "#bcdf59",
  "#ffca58",
  "#49cae4",
  "#a093e2",
  "#aee8f4",
  "#fcfcfc"
  ]
