# Base16 Atelier Lakeside - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#161b1d"
foreground = "#7ea2b4"

cursor_bg = "#1f292e"
cursor_border = "#7ea2b4"
cursor_fg = "#c1e4f6"

selection_bg = "#7ea2b4"
selection_fg = "#161b1d"

ansi = [
  "#161b1d",
  "#d22d72",
  "#568c3b",
  "#8a8a0f",
  "#257fad",
  "#6b6bb8",
  "#2d8f6f",
  "#c1e4f6"
  ]
brights = [
  "#5a7b8c",
  "#d22d72",
  "#568c3b",
  "#8a8a0f",
  "#257fad",
  "#6b6bb8",
  "#2d8f6f",
  "#ebf8ff"
  ]
