# Base16 selenized-white - wezterm color config
# Scheme by Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
[colors]
background = "#ffffff"
foreground = "#474747"

cursor_bg = "#ebebeb"
cursor_border = "#474747"
cursor_fg = "#282828"

selection_bg = "#474747"
selection_fg = "#ffffff"

ansi = [
  "#ffffff",
  "#bf0000",
  "#008400",
  "#af8500",
  "#0054cf",
  "#6b40c3",
  "#009a8a",
  "#282828"
  ]
brights = [
  "#878787",
  "#bf0000",
  "#008400",
  "#af8500",
  "#0054cf",
  "#6b40c3",
  "#009a8a",
  "#282828"
  ]

[colors.indexed]
16 = "#ba3700"
17 = "#dd0f9d"
18 = "#ebebeb"
19 = "#cdcdcd"
20 = "#878787"
21 = "#474747"
