# Base16 Atelier Seaside Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#f4fbf4"
foreground = "#5e6e5e"

cursor_bg = "#cfe8cf"
cursor_border = "#5e6e5e"
cursor_fg = "#242924"

selection_bg = "#5e6e5e"
selection_fg = "#f4fbf4"

ansi = [
  "#f4fbf4",
  "#e6193c",
  "#29a329",
  "#98981b",
  "#3d62f5",
  "#ad2bee",
  "#1999b3",
  "#242924"
  ]
brights = [
  "#809980",
  "#e6193c",
  "#29a329",
  "#98981b",
  "#3d62f5",
  "#ad2bee",
  "#1999b3",
  "#131513"
  ]
