# Base16 Catppuccin Latte - wezterm color config
# Scheme by https://github.com/catppuccin/catppuccin
[colors]
background = "#eff1f5"
foreground = "#4c4f69"

cursor_bg = "#e6e9ef"
cursor_border = "#4c4f69"
cursor_fg = "#dc8a78"

selection_bg = "#4c4f69"
selection_fg = "#eff1f5"

ansi = [
  "#eff1f5",
  "#d20f39",
  "#40a02b",
  "#df8e1d",
  "#1e66f5",
  "#8839ef",
  "#179299",
  "#dc8a78"
  ]
brights = [
  "#bcc0cc",
  "#d20f39",
  "#40a02b",
  "#df8e1d",
  "#1e66f5",
  "#8839ef",
  "#179299",
  "#7287fd"
  ]

[colors.indexed]
16 = "#fe640b"
17 = "#dd7878"
18 = "#e6e9ef"
19 = "#ccd0da"
20 = "#acb0be"
21 = "#4c4f69"
