# Base16 Eighties - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#2d2d2d"
foreground = "#d3d0c8"

cursor_bg = "#393939"
cursor_border = "#d3d0c8"
cursor_fg = "#e8e6df"

selection_bg = "#d3d0c8"
selection_fg = "#2d2d2d"

ansi = [
  "#2d2d2d",
  "#f2777a",
  "#99cc99",
  "#ffcc66",
  "#6699cc",
  "#cc99cc",
  "#66cccc",
  "#e8e6df"
  ]
brights = [
  "#747369",
  "#f2777a",
  "#99cc99",
  "#ffcc66",
  "#6699cc",
  "#cc99cc",
  "#66cccc",
  "#f2f0ec"
  ]

[colors.indexed]
16 = "#f99157"
17 = "#d27b53"
18 = "#393939"
19 = "#515151"
20 = "#a09f93"
21 = "#d3d0c8"
