# Base16 Solar Flare Light - wezterm color config
# Scheme by Chuck Harmston (https://chuck.harmston.ch)
[colors]
background = "#f5f7fa"
foreground = "#586875"

cursor_bg = "#586875"
cursor_border = "#586875"
cursor_fg = "#f5f7fa"

selection_bg = "#586875"
selection_fg = "#f5f7fa"

ansi = [
  "#f5f7fa",
  "#ef5253",
  "#7cc844",
  "#e4b51c",
  "#33b5e1",
  "#a363d5",
  "#52cbb0",
  "#222e38"
  ]
brights = [
  "#85939e",
  "#ef5253",
  "#7cc844",
  "#e4b51c",
  "#33b5e1",
  "#a363d5",
  "#52cbb0",
  "#18262f"
  ]

[colors.indexed]
16 = "#e66b2b"
17 = "#d73c9a"
18 = "#e8e9ed"
19 = "#a6afb8"
20 = "#667581"
21 = "#586875"
