# Base16 Classic Light - wezterm color config
# Scheme by Jason Heeris (http://heeris.id.au)
[colors]
background = "#f5f5f5"
foreground = "#303030"

cursor_bg = "#e0e0e0"
cursor_border = "#303030"
cursor_fg = "#202020"

selection_bg = "#303030"
selection_fg = "#f5f5f5"

ansi = [
  "#f5f5f5",
  "#ac4142",
  "#90a959",
  "#f4bf75",
  "#6a9fb5",
  "#aa759f",
  "#75b5aa",
  "#202020"
  ]
brights = [
  "#b0b0b0",
  "#ac4142",
  "#90a959",
  "#f4bf75",
  "#6a9fb5",
  "#aa759f",
  "#75b5aa",
  "#151515"
  ]

[colors.indexed]
16 = "#d28445"
17 = "#8f5536"
18 = "#e0e0e0"
19 = "#d0d0d0"
20 = "#505050"
21 = "#303030"
