# Base16 Gruvbox Material Dark, Hard - wezterm color config
# Scheme by Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
[colors]
background = "#202020"
foreground = "#ddc7a1"

cursor_bg = "#2a2827"
cursor_border = "#ddc7a1"
cursor_fg = "#ebdbb2"

selection_bg = "#ddc7a1"
selection_fg = "#202020"

ansi = [
  "#202020",
  "#ea6962",
  "#a9b665",
  "#d8a657",
  "#7daea3",
  "#d3869b",
  "#89b482",
  "#ebdbb2"
  ]
brights = [
  "#5a524c",
  "#ea6962",
  "#a9b665",
  "#d8a657",
  "#7daea3",
  "#d3869b",
  "#89b482",
  "#fbf1c7"
  ]
