# Base16 Rosé Pine Dawn - wezterm color config
# Scheme by Emilia Dunfelt &lt;edun@dunfelt.se&gt;
[colors]
background = "#faf4ed"
foreground = "#575279"

cursor_bg = "#fffaf3"
cursor_border = "#575279"
cursor_fg = "#575279"

selection_bg = "#575279"
selection_fg = "#faf4ed"

ansi = [
  "#faf4ed",
  "#b4637a",
  "#286983",
  "#d7827e",
  "#907aa9",
  "#ea9d34",
  "#56949f",
  "#575279"
  ]
brights = [
  "#9893a5",
  "#b4637a",
  "#286983",
  "#d7827e",
  "#907aa9",
  "#ea9d34",
  "#56949f",
  "#cecacd"
  ]

[colors.indexed]
16 = "#ea9d34"
17 = "#cecacd"
18 = "#fffaf3"
19 = "#f2e9de"
20 = "#797593"
21 = "#575279"
