# Base16 Gruvbox Material Dark, Soft - wezterm color config
# Scheme by Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
[colors]
background = "#32302f"
foreground = "#ddc7a1"

cursor_bg = "#ddc7a1"
cursor_border = "#ddc7a1"
cursor_fg = "#32302f"

selection_bg = "#ddc7a1"
selection_fg = "#32302f"

ansi = [
  "#32302f",
  "#ea6962",
  "#a9b665",
  "#d8a657",
  "#7daea3",
  "#d3869b",
  "#89b482",
  "#ebdbb2"
  ]
brights = [
  "#7c6f64",
  "#ea6962",
  "#a9b665",
  "#d8a657",
  "#7daea3",
  "#d3869b",
  "#89b482",
  "#fbf1c7"
  ]

[colors.indexed]
16 = "#e78a4e"
17 = "#bd6f3e"
18 = "#3c3836"
19 = "#5a524c"
20 = "#bdae93"
21 = "#ddc7a1"
