# Base16 Windows High Contrast - wezterm color config
# Scheme by Fergus Collins (https://github.com/ferguscollins)
[colors]
background = "#000000"
foreground = "#c0c0c0"

cursor_bg = "#1c1c1c"
cursor_border = "#c0c0c0"
cursor_fg = "#dedede"

selection_bg = "#c0c0c0"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#fc5454",
  "#54fc54",
  "#fcfc54",
  "#5454fc",
  "#fc54fc",
  "#54fcfc",
  "#dedede"
  ]
brights = [
  "#545454",
  "#fc5454",
  "#54fc54",
  "#fcfc54",
  "#5454fc",
  "#fc54fc",
  "#54fcfc",
  "#fcfcfc"
  ]

[colors.indexed]
16 = "#808000"
17 = "#008000"
18 = "#1c1c1c"
19 = "#383838"
20 = "#a2a2a2"
21 = "#c0c0c0"
