# Base16 IR Black - wezterm color config
# Scheme by Timothée Poisot (http://timotheepoisot.fr)
[colors]
background = "#000000"
foreground = "#b5b3aa"

cursor_bg = "#b5b3aa"
cursor_border = "#b5b3aa"
cursor_fg = "#000000"

selection_bg = "#b5b3aa"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#ff6c60",
  "#a8ff60",
  "#ffffb6",
  "#96cbfe",
  "#ff73fd",
  "#c6c5fe",
  "#d9d7cc"
  ]
brights = [
  "#6c6c66",
  "#ff6c60",
  "#a8ff60",
  "#ffffb6",
  "#96cbfe",
  "#ff73fd",
  "#c6c5fe",
  "#fdfbee"
  ]
