# Base16 Classic Dark - wezterm color config
# Scheme by Jason Heeris (http://heeris.id.au)
[colors]
background = "#151515"
foreground = "#d0d0d0"

cursor_bg = "#202020"
cursor_border = "#d0d0d0"
cursor_fg = "#e0e0e0"

selection_bg = "#d0d0d0"
selection_fg = "#151515"

ansi = [
  "#151515",
  "#ac4142",
  "#90a959",
  "#f4bf75",
  "#6a9fb5",
  "#aa759f",
  "#75b5aa",
  "#e0e0e0"
  ]
brights = [
  "#505050",
  "#ac4142",
  "#90a959",
  "#f4bf75",
  "#6a9fb5",
  "#aa759f",
  "#75b5aa",
  "#f5f5f5"
  ]
