# Base16 Tokyo Night Dark - wezterm color config
# Scheme by Michaël Ball
[colors]
background = "#1a1b26"
foreground = "#a9b1d6"

cursor_bg = "#16161e"
cursor_border = "#a9b1d6"
cursor_fg = "#cbccd1"

selection_bg = "#a9b1d6"
selection_fg = "#1a1b26"

ansi = [
  "#1a1b26",
  "#c0caf5",
  "#9ece6a",
  "#0db9d7",
  "#2ac3de",
  "#bb9af7",
  "#b4f9f8",
  "#cbccd1"
  ]
brights = [
  "#444b6a",
  "#c0caf5",
  "#9ece6a",
  "#0db9d7",
  "#2ac3de",
  "#bb9af7",
  "#b4f9f8",
  "#d5d6db"
  ]
