# Base16 Harmonic16 Dark - wezterm color config
# Scheme by Jannik Siebert (https://github.com/janniks)
[colors]
background = "#0b1c2c"
foreground = "#cbd6e2"

cursor_bg = "#cbd6e2"
cursor_border = "#cbd6e2"
cursor_fg = "#0b1c2c"

selection_bg = "#cbd6e2"
selection_fg = "#0b1c2c"

ansi = [
  "#0b1c2c",
  "#bf8b56",
  "#56bf8b",
  "#8bbf56",
  "#8b56bf",
  "#bf568b",
  "#568bbf",
  "#e5ebf1"
  ]
brights = [
  "#627e99",
  "#bf8b56",
  "#56bf8b",
  "#8bbf56",
  "#8b56bf",
  "#bf568b",
  "#568bbf",
  "#f7f9fb"
  ]

[colors.indexed]
16 = "#bfbf56"
17 = "#bf5656"
18 = "#223b54"
19 = "#405c79"
20 = "#aabcce"
21 = "#cbd6e2"
