# Base16 Solarized Light - wezterm color config
# Scheme by Ethan Schoonover (modified by aramisgithub)
[colors]
background = "#fdf6e3"
foreground = "#586e75"

cursor_bg = "#586e75"
cursor_border = "#586e75"
cursor_fg = "#fdf6e3"

selection_bg = "#586e75"
selection_fg = "#fdf6e3"

ansi = [
  "#fdf6e3",
  "#dc322f",
  "#859900",
  "#b58900",
  "#268bd2",
  "#6c71c4",
  "#2aa198",
  "#073642"
  ]
brights = [
  "#839496",
  "#dc322f",
  "#859900",
  "#b58900",
  "#268bd2",
  "#6c71c4",
  "#2aa198",
  "#002b36"
  ]

[colors.indexed]
16 = "#cb4b16"
17 = "#d33682"
18 = "#eee8d5"
19 = "#93a1a1"
20 = "#657b83"
21 = "#586e75"
