# Base16 Ocean - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#2b303b"
foreground = "#c0c5ce"

cursor_bg = "#343d46"
cursor_border = "#c0c5ce"
cursor_fg = "#dfe1e8"

selection_bg = "#c0c5ce"
selection_fg = "#2b303b"

ansi = [
  "#2b303b",
  "#bf616a",
  "#a3be8c",
  "#ebcb8b",
  "#8fa1b3",
  "#b48ead",
  "#96b5b4",
  "#dfe1e8"
  ]
brights = [
  "#65737e",
  "#bf616a",
  "#a3be8c",
  "#ebcb8b",
  "#8fa1b3",
  "#b48ead",
  "#96b5b4",
  "#eff1f5"
  ]
