# Base16 Catppuccin Macchiato - wezterm color config
# Scheme by https://github.com/catppuccin/catppuccin
[colors]
background = "#24273a"
foreground = "#cad3f5"

cursor_bg = "#1e2030"
cursor_border = "#cad3f5"
cursor_fg = "#f4dbd6"

selection_bg = "#cad3f5"
selection_fg = "#24273a"

ansi = [
  "#24273a",
  "#ed8796",
  "#a6da95",
  "#eed49f",
  "#8aadf4",
  "#c6a0f6",
  "#8bd5ca",
  "#f4dbd6"
  ]
brights = [
  "#494d64",
  "#ed8796",
  "#a6da95",
  "#eed49f",
  "#8aadf4",
  "#c6a0f6",
  "#8bd5ca",
  "#b7bdf8"
  ]
