# Base16 Material Palenight - wezterm color config
# Scheme by Nate Peterson
[colors]
background = "#292d3e"
foreground = "#959dcb"

cursor_bg = "#959dcb"
cursor_border = "#959dcb"
cursor_fg = "#292d3e"

selection_bg = "#959dcb"
selection_fg = "#292d3e"

ansi = [
  "#292d3e",
  "#f07178",
  "#c3e88d",
  "#ffcb6b",
  "#82aaff",
  "#c792ea",
  "#89ddff",
  "#959dcb"
  ]
brights = [
  "#676e95",
  "#f07178",
  "#c3e88d",
  "#ffcb6b",
  "#82aaff",
  "#c792ea",
  "#89ddff",
  "#ffffff"
  ]

[colors.indexed]
16 = "#f78c6c"
17 = "#ff5370"
18 = "#444267"
19 = "#32374d"
20 = "#8796b0"
21 = "#959dcb"
