# Base16 selenized-white - wezterm color config
# Scheme by Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
[colors]
background = "#ffffff"
foreground = "#474747"

cursor_bg = "#474747"
cursor_border = "#474747"
cursor_fg = "#ffffff"

selection_bg = "#474747"
selection_fg = "#ffffff"

ansi = [
  "#ffffff",
  "#bf0000",
  "#008400",
  "#af8500",
  "#0054cf",
  "#6b40c3",
  "#009a8a",
  "#282828"
  ]
brights = [
  "#878787",
  "#bf0000",
  "#008400",
  "#af8500",
  "#0054cf",
  "#6b40c3",
  "#009a8a",
  "#282828"
  ]
