# Base16 OceanicNext - wezterm color config
# Scheme by https://github.com/voronianski/oceanic-next-color-scheme
[colors]
background = "#1b2b34"
foreground = "#c0c5ce"

cursor_bg = "#c0c5ce"
cursor_border = "#c0c5ce"
cursor_fg = "#1b2b34"

selection_bg = "#c0c5ce"
selection_fg = "#1b2b34"

ansi = [
  "#1b2b34",
  "#ec5f67",
  "#99c794",
  "#fac863",
  "#6699cc",
  "#c594c5",
  "#5fb3b3",
  "#cdd3de"
  ]
brights = [
  "#65737e",
  "#ec5f67",
  "#99c794",
  "#fac863",
  "#6699cc",
  "#c594c5",
  "#5fb3b3",
  "#d8dee9"
  ]

[colors.indexed]
16 = "#f99157"
17 = "#ab7967"
18 = "#343d46"
19 = "#4f5b66"
20 = "#a7adba"
21 = "#c0c5ce"
