# Base16 Gruvbox dark - wezterm color config
# Scheme by Tinted Theming (https://github.com/tinted-theming), morhetz (https://github.com/morhetz/gruvbox)
[colors]
background = "#282828"
foreground = "#ebdbb2"

cursor_bg = "#3c3836"
cursor_border = "#ebdbb2"
cursor_fg = "#fbf1c7"

selection_bg = "#ebdbb2"
selection_fg = "#282828"

ansi = [
  "#282828",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#fbf1c7"
  ]
brights = [
  "#665c54",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#f9f5d7"
  ]
