# base16 London
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#ffffff"
foreground = "#333333"

cursor_bg = "#333333"
cursor_border = "#333333"
cursor_fg = "#ffffff"

selection_bg = "#333333"
selection_fg = "#e7e7e7"

ansi = [
  "#ffffff",
  "#333333",
  "#444444",
  "#555555",
  "#666666",
  "#777777",
  "#888888",
  "#333333"
]
brights = [
  "#333333",
  "#333333",
  "#444444",
  "#555555",
  "#666666",
  "#777777",
  "#888888",
  "#aaaaaa"
]

[colors.indexed]
16 = "#444444"
17 = "#303030"
18 = "#f1f1f1"
19 = "#e7e7e7"
20 = "#7a7a7a"
21 = "#242424"
