# Base16 Unikitty Dark - wezterm color config
# Scheme by Josh W Lewis (@joshwlewis)
[colors]
background = "#2e2a31"
foreground = "#bcbabe"

cursor_bg = "#bcbabe"
cursor_border = "#bcbabe"
cursor_fg = "#2e2a31"

selection_bg = "#bcbabe"
selection_fg = "#2e2a31"

ansi = [
  "#2e2a31",
  "#d8137f",
  "#17ad98",
  "#dc8a0e",
  "#796af5",
  "#bb60ea",
  "#149bda",
  "#d8d7da"
  ]
brights = [
  "#838085",
  "#d8137f",
  "#17ad98",
  "#dc8a0e",
  "#796af5",
  "#bb60ea",
  "#149bda",
  "#f5f4f7"
  ]
