# Base16 Github - wezterm color config
# Scheme by Tinted Theming (https://github.com/tinted-theming)
[colors]
background = "#eaeef2"
foreground = "#424a53"

cursor_bg = "#d0d7de"
cursor_border = "#424a53"
cursor_fg = "#32383f"

selection_bg = "#424a53"
selection_fg = "#eaeef2"

ansi = [
  "#eaeef2",
  "#fa4549",
  "#2da44e",
  "#bf8700",
  "#218bff",
  "#a475f9",
  "#339d9b",
  "#32383f"
  ]
brights = [
  "#8c959f",
  "#fa4549",
  "#2da44e",
  "#bf8700",
  "#218bff",
  "#a475f9",
  "#339d9b",
  "#1f2328"
  ]
