# Base16 Still Alive - wezterm color config
# Scheme by Derrick McKee (derrick.mckee@gmail.com)
[colors]
background = "#f0f0f0"
foreground = "#d80000"

cursor_bg = "#f0d848"
cursor_border = "#d80000"
cursor_fg = "#489000"

selection_bg = "#d80000"
selection_fg = "#f0f0f0"

ansi = [
  "#f0f0f0",
  "#487830",
  "#5c5c6a",
  "#426395",
  "#001878",
  "#900000",
  "#2c3c57",
  "#489000"
  ]
brights = [
  "#f01818",
  "#487830",
  "#5c5c6a",
  "#426395",
  "#001878",
  "#900000",
  "#2c3c57",
  "#30a860"
  ]

[colors.indexed]
16 = "#183048"
17 = "#140c0d"
18 = "#f0d848"
19 = "#fff018"
20 = "#f00000"
21 = "#d80000"
