# Base16 Materia - wezterm color config
# Scheme by Defman21
[colors]
background = "#263238"
foreground = "#cdd3de"

cursor_bg = "#cdd3de"
cursor_border = "#cdd3de"
cursor_fg = "#263238"

selection_bg = "#cdd3de"
selection_fg = "#263238"

ansi = [
  "#263238",
  "#ec5f67",
  "#8bd649",
  "#ffcc00",
  "#89ddff",
  "#82aaff",
  "#80cbc4",
  "#d5dbe5"
  ]
brights = [
  "#707880",
  "#ec5f67",
  "#8bd649",
  "#ffcc00",
  "#89ddff",
  "#82aaff",
  "#80cbc4",
  "#ffffff"
  ]
