# Base16 Seti UI - wezterm color config
# Scheme by 
[colors]
background = "#151718"
foreground = "#d6d6d6"

cursor_bg = "#d6d6d6"
cursor_border = "#d6d6d6"
cursor_fg = "#151718"

selection_bg = "#d6d6d6"
selection_fg = "#151718"

ansi = [
  "#151718",
  "#cd3f45",
  "#9fca56",
  "#e6cd69",
  "#55b5db",
  "#a074c4",
  "#55dbbe",
  "#eeeeee"
  ]
brights = [
  "#41535b",
  "#cd3f45",
  "#9fca56",
  "#e6cd69",
  "#55b5db",
  "#a074c4",
  "#55dbbe",
  "#ffffff"
  ]

[colors.indexed]
16 = "#db7b55"
17 = "#8a553f"
18 = "#282a2b"
19 = "#3b758c"
20 = "#43a5d5"
21 = "#d6d6d6"
