# Base16 Digital Rain - wezterm color config
# Scheme by Nathan Byrd (https://github.com/cognitivegears)
[colors]
background = "#000000"
foreground = "#00ff00"

cursor_bg = "#4a806c"
cursor_border = "#00ff00"
cursor_fg = "#c4cec4"

selection_bg = "#00ff00"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#c85a46",
  "#64c83c",
  "#a67a50",
  "#5482af",
  "#9472b4",
  "#468c78",
  "#c4cec4"
  ]
brights = [
  "#7c8d7c",
  "#c85a46",
  "#64c83c",
  "#a67a50",
  "#5482af",
  "#9472b4",
  "#468c78",
  "#d8e2dc"
  ]
