# Base16 Atelier Savanna - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#171c19"
foreground = "#87928a"

cursor_bg = "#232a25"
cursor_border = "#87928a"
cursor_fg = "#dfe7e2"

selection_bg = "#87928a"
selection_fg = "#171c19"

ansi = [
  "#171c19",
  "#b16139",
  "#489963",
  "#a07e3b",
  "#478c90",
  "#55859b",
  "#1c9aa0",
  "#dfe7e2"
  ]
brights = [
  "#5f6d64",
  "#b16139",
  "#489963",
  "#a07e3b",
  "#478c90",
  "#55859b",
  "#1c9aa0",
  "#ecf4ee"
  ]
