# Base16 Atelier Sulphurpool - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#202746"
foreground = "#979db4"

cursor_bg = "#293256"
cursor_border = "#979db4"
cursor_fg = "#dfe2f1"

selection_bg = "#979db4"
selection_fg = "#202746"

ansi = [
  "#202746",
  "#c94922",
  "#ac9739",
  "#c08b30",
  "#3d8fd1",
  "#6679cc",
  "#22a2c9",
  "#dfe2f1"
  ]
brights = [
  "#6b7394",
  "#c94922",
  "#ac9739",
  "#c08b30",
  "#3d8fd1",
  "#6679cc",
  "#22a2c9",
  "#f5f7ff"
  ]
