# Base16 IR Black - wezterm color config
# Scheme by Timothée Poisot (http://timotheepoisot.fr)
[colors]
background = "#000000"
foreground = "#b5b3aa"

cursor_bg = "#242422"
cursor_border = "#b5b3aa"
cursor_fg = "#d9d7cc"

selection_bg = "#b5b3aa"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#ff6c60",
  "#a8ff60",
  "#ffffb6",
  "#96cbfe",
  "#ff73fd",
  "#c6c5fe",
  "#d9d7cc"
  ]
brights = [
  "#6c6c66",
  "#ff6c60",
  "#a8ff60",
  "#ffffb6",
  "#96cbfe",
  "#ff73fd",
  "#c6c5fe",
  "#fdfbee"
  ]

[colors.indexed]
16 = "#e9c062"
17 = "#b18a3d"
18 = "#242422"
19 = "#484844"
20 = "#918f88"
21 = "#b5b3aa"
