# Base16 Espresso - wezterm color config
# Scheme by Unknown. Maintained by Alex Mirrington (https://github.com/alexmirrington)
[colors]
background = "#2d2d2d"
foreground = "#cccccc"

cursor_bg = "#393939"
cursor_border = "#cccccc"
cursor_fg = "#e0e0e0"

selection_bg = "#cccccc"
selection_fg = "#2d2d2d"

ansi = [
  "#2d2d2d",
  "#d25252",
  "#a5c261",
  "#ffc66d",
  "#6c99bb",
  "#d197d9",
  "#bed6ff",
  "#e0e0e0"
  ]
brights = [
  "#777777",
  "#d25252",
  "#a5c261",
  "#ffc66d",
  "#6c99bb",
  "#d197d9",
  "#bed6ff",
  "#ffffff"
  ]
