# base16 Ayu Dark
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#0f1419"
foreground = "#e6e1cf"

cursor_bg = "#e6e1cf"
cursor_border = "#e6e1cf"
cursor_fg = "#0f1419"

selection_bg = "#e6e1cf"
selection_fg = "#272d38"

ansi = [
  "#0f1419",
  "#f07178",
  "#b8cc52",
  "#ffb454",
  "#59c2ff",
  "#d2a6ff",
  "#95e6cb",
  "#e6e1cf"
]
brights = [
  "#272d38",
  "#f07178",
  "#b8cc52",
  "#ffb454",
  "#59c2ff",
  "#d2a6ff",
  "#95e6cb",
  "#f3f4f5"
]

[colors.indexed]
16 = "#ff8f40"
17 = "#e6b673"
18 = "#131721"
19 = "#272d38"
20 = "#bfbdb6"
21 = "#e6e1cf"
