# Base16 Edge Light - wezterm color config
# Scheme by cjayross (https://github.com/cjayross)
[colors]
background = "#fafafa"
foreground = "#5e646f"

cursor_bg = "#7c9f4b"
cursor_border = "#5e646f"
cursor_fg = "#b870ce"

selection_bg = "#5e646f"
selection_fg = "#fafafa"

ansi = [
  "#fafafa",
  "#db7070",
  "#7c9f4b",
  "#d69822",
  "#6587bf",
  "#b870ce",
  "#509c93",
  "#b870ce"
  ]
brights = [
  "#5e646f",
  "#db7070",
  "#7c9f4b",
  "#d69822",
  "#6587bf",
  "#b870ce",
  "#509c93",
  "#5e646f"
  ]

[colors.indexed]
16 = "#db7070"
17 = "#509c93"
18 = "#7c9f4b"
19 = "#d69822"
20 = "#6587bf"
21 = "#5e646f"
