# base24 Github Light High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#ffffff"
foreground = "#454c54"

cursor_bg = "#454c54"
cursor_border = "#454c54"
cursor_fg = "#ffffff"

selection_bg = "#454c54"
selection_fg = "#d1d9e0"

ansi = [
  "#ffffff",
  "#a0111f",
  "#024c1a",
  "#603700",
  "#0349b4",
  "#622cbc",
  "#1b7c83",
  "#454c54"
]
brights = [
  "#818b98",
  "#86061d",
  "#055d20",
  "#4e2c00",
  "#1168e3",
  "#844ae7",
  "#3192aa",
  "#010409"
]

[colors.indexed]
16 = "#702c00"
17 = "#86061d"
18 = "#f6f8fa"
19 = "#d1d9e0"
20 = "#59636e"
21 = "#25292e"
