# Base16 Google Dark - wezterm color config
# Scheme by Seth Wright (http://sethawright.com)
[colors]
background = "#1d1f21"
foreground = "#c5c8c6"

cursor_bg = "#282a2e"
cursor_border = "#c5c8c6"
cursor_fg = "#e0e0e0"

selection_bg = "#c5c8c6"
selection_fg = "#1d1f21"

ansi = [
  "#1d1f21",
  "#cc342b",
  "#198844",
  "#fba922",
  "#3971ed",
  "#a36ac7",
  "#3971ed",
  "#e0e0e0"
  ]
brights = [
  "#969896",
  "#cc342b",
  "#198844",
  "#fba922",
  "#3971ed",
  "#a36ac7",
  "#3971ed",
  "#ffffff"
  ]
