# Base16 Silk Dark - wezterm color config
# Scheme by Gabriel Fontes (https://github.com/Misterio77)
[colors]
background = "#0e3c46"
foreground = "#c7dbdd"

cursor_bg = "#c7dbdd"
cursor_border = "#c7dbdd"
cursor_fg = "#0e3c46"

selection_bg = "#c7dbdd"
selection_fg = "#0e3c46"

ansi = [
  "#0e3c46",
  "#fb6953",
  "#73d8ad",
  "#fce380",
  "#46bddd",
  "#756b8a",
  "#3fb2b9",
  "#cbf2f7"
  ]
brights = [
  "#587073",
  "#fb6953",
  "#73d8ad",
  "#fce380",
  "#46bddd",
  "#756b8a",
  "#3fb2b9",
  "#d2faff"
  ]

[colors.indexed]
16 = "#fcab74"
17 = "#9b647b"
18 = "#1d494e"
19 = "#2a5054"
20 = "#9dc8cd"
21 = "#c7dbdd"
