# Base16 Da One Ocean - wezterm color config
# Scheme by NNB (https://github.com/NNBnh)
[colors]
background = "#171726"
foreground = "#ffffff"

cursor_bg = "#22273d"
cursor_border = "#ffffff"
cursor_fg = "#ffffff"

selection_bg = "#ffffff"
selection_fg = "#171726"

ansi = [
  "#171726",
  "#fa7883",
  "#98c379",
  "#ff9470",
  "#6bb8ff",
  "#e799ff",
  "#8af5ff",
  "#ffffff"
  ]
brights = [
  "#878d96",
  "#fa7883",
  "#98c379",
  "#ff9470",
  "#6bb8ff",
  "#e799ff",
  "#8af5ff",
  "#ffffff"
  ]
