# Base16 Blue Forest - wezterm color config
# Scheme by alonsodomin (https://github.com/alonsodomin)
[colors]
background = "#141f2e"
foreground = "#ffcc33"

cursor_bg = "#ffcc33"
cursor_border = "#ffcc33"
cursor_fg = "#141f2e"

selection_bg = "#ffcc33"
selection_fg = "#141f2e"

ansi = [
  "#141f2e",
  "#fffab1",
  "#80ff80",
  "#91ccff",
  "#a2cff5",
  "#0099ff",
  "#80ff80",
  "#91ccff"
  ]
brights = [
  "#a0ffa0",
  "#fffab1",
  "#80ff80",
  "#91ccff",
  "#a2cff5",
  "#0099ff",
  "#80ff80",
  "#375780"
  ]

[colors.indexed]
16 = "#ff8080"
17 = "#e7e7e7"
18 = "#1e5c1e"
19 = "#273e5c"
20 = "#1e5c1e"
21 = "#ffcc33"
