# base16 Ayu Light
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#fafafa"
foreground = "#5c6773"

cursor_bg = "#5c6773"
cursor_border = "#5c6773"
cursor_fg = "#fafafa"

selection_bg = "#5c6773"
selection_fg = "#f8f9fa"

ansi = [
  "#fafafa",
  "#f07178",
  "#86b300",
  "#f2ae49",
  "#36a3d9",
  "#a37acc",
  "#4cbf99",
  "#242936"
]
brights = [
  "#f8f9fa",
  "#f07178",
  "#86b300",
  "#f2ae49",
  "#36a3d9",
  "#a37acc",
  "#4cbf99",
  "#1a1f29"
]

[colors.indexed]
16 = "#fa8d3e"
17 = "#e6ba7e"
18 = "#f3f4f5"
19 = "#f8f9fa"
20 = "#828c99"
21 = "#5c6773"
