# Base16 Snazzy - wezterm color config
# Scheme by Chawye Hsu (https://github.com/chawyehsu), based on Hyper Snazzy Theme (https://github.com/sindresorhus/hyper-snazzy)
[colors]
background = "#282a36"
foreground = "#e2e4e5"

cursor_bg = "#34353e"
cursor_border = "#e2e4e5"
cursor_fg = "#eff0eb"

selection_bg = "#e2e4e5"
selection_fg = "#282a36"

ansi = [
  "#282a36",
  "#ff5c57",
  "#5af78e",
  "#f3f99d",
  "#57c7ff",
  "#ff6ac1",
  "#9aedfe",
  "#eff0eb"
  ]
brights = [
  "#78787e",
  "#ff5c57",
  "#5af78e",
  "#f3f99d",
  "#57c7ff",
  "#ff6ac1",
  "#9aedfe",
  "#f1f1f0"
  ]

[colors.indexed]
16 = "#ff9f43"
17 = "#b2643c"
18 = "#34353e"
19 = "#43454f"
20 = "#a5a5a9"
21 = "#e2e4e5"
