# Base16 Sandcastle - wezterm color config
# Scheme by George Essig (https://github.com/gessig)
[colors]
background = "#282c34"
foreground = "#a89984"

cursor_bg = "#2c323b"
cursor_border = "#a89984"
cursor_fg = "#d5c4a1"

selection_bg = "#a89984"
selection_fg = "#282c34"

ansi = [
  "#282c34",
  "#83a598",
  "#528b8b",
  "#a07e3b",
  "#83a598",
  "#d75f5f",
  "#83a598",
  "#d5c4a1"
  ]
brights = [
  "#665c54",
  "#83a598",
  "#528b8b",
  "#a07e3b",
  "#83a598",
  "#d75f5f",
  "#83a598",
  "#fdf4c1"
  ]

[colors.indexed]
16 = "#a07e3b"
17 = "#a87322"
18 = "#2c323b"
19 = "#3e4451"
20 = "#928374"
21 = "#a89984"
