# Base16 Espresso - wezterm color config
# Scheme by Unknown. Maintained by Alex Mirrington (https://github.com/alexmirrington)
[colors]
background = "#2d2d2d"
foreground = "#cccccc"

cursor_bg = "#cccccc"
cursor_border = "#cccccc"
cursor_fg = "#2d2d2d"

selection_bg = "#cccccc"
selection_fg = "#2d2d2d"

ansi = [
  "#2d2d2d",
  "#d25252",
  "#a5c261",
  "#ffc66d",
  "#6c99bb",
  "#d197d9",
  "#bed6ff",
  "#e0e0e0"
  ]
brights = [
  "#777777",
  "#d25252",
  "#a5c261",
  "#ffc66d",
  "#6c99bb",
  "#d197d9",
  "#bed6ff",
  "#ffffff"
  ]

[colors.indexed]
16 = "#f9a959"
17 = "#f97394"
18 = "#393939"
19 = "#515151"
20 = "#b4b7b4"
21 = "#cccccc"
