# Base16 Gruvbox light, medium - wezterm color config
# Scheme by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
[colors]
background = "#fbf1c7"
foreground = "#504945"

cursor_bg = "#504945"
cursor_border = "#504945"
cursor_fg = "#fbf1c7"

selection_bg = "#504945"
selection_fg = "#fbf1c7"

ansi = [
  "#fbf1c7",
  "#9d0006",
  "#79740e",
  "#b57614",
  "#076678",
  "#8f3f71",
  "#427b58",
  "#3c3836"
  ]
brights = [
  "#bdae93",
  "#9d0006",
  "#79740e",
  "#b57614",
  "#076678",
  "#8f3f71",
  "#427b58",
  "#282828"
  ]

[colors.indexed]
16 = "#af3a03"
17 = "#d65d0e"
18 = "#ebdbb2"
19 = "#d5c4a1"
20 = "#665c54"
21 = "#504945"
