# Base16 Mexico Light - wezterm color config
# Scheme by Sheldon Johnson
[colors]
background = "#f8f8f8"
foreground = "#383838"

cursor_bg = "#e8e8e8"
cursor_border = "#383838"
cursor_fg = "#282828"

selection_bg = "#383838"
selection_fg = "#f8f8f8"

ansi = [
  "#f8f8f8",
  "#ab4642",
  "#538947",
  "#f79a0e",
  "#7cafc2",
  "#96609e",
  "#4b8093",
  "#282828"
  ]
brights = [
  "#b8b8b8",
  "#ab4642",
  "#538947",
  "#f79a0e",
  "#7cafc2",
  "#96609e",
  "#4b8093",
  "#181818"
  ]

[colors.indexed]
16 = "#dc9656"
17 = "#a16946"
18 = "#e8e8e8"
19 = "#d8d8d8"
20 = "#585858"
21 = "#383838"
