# Base16 Gruvbox dark, soft - wezterm color config
# Scheme by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
[colors]
background = "#32302f"
foreground = "#d5c4a1"

cursor_bg = "#3c3836"
cursor_border = "#d5c4a1"
cursor_fg = "#ebdbb2"

selection_bg = "#d5c4a1"
selection_fg = "#32302f"

ansi = [
  "#32302f",
  "#fb4934",
  "#b8bb26",
  "#fabd2f",
  "#83a598",
  "#d3869b",
  "#8ec07c",
  "#ebdbb2"
  ]
brights = [
  "#665c54",
  "#fb4934",
  "#b8bb26",
  "#fabd2f",
  "#83a598",
  "#d3869b",
  "#8ec07c",
  "#fbf1c7"
  ]

[colors.indexed]
16 = "#fe8019"
17 = "#d65d0e"
18 = "#3c3836"
19 = "#504945"
20 = "#bdae93"
21 = "#d5c4a1"
