# Base16 Unikitty Light - wezterm color config
# Scheme by Josh W Lewis (@joshwlewis)
[colors]
background = "#ffffff"
foreground = "#6c696e"

cursor_bg = "#e1e1e2"
cursor_border = "#6c696e"
cursor_fg = "#4f4b51"

selection_bg = "#6c696e"
selection_fg = "#ffffff"

ansi = [
  "#ffffff",
  "#d8137f",
  "#17ad98",
  "#dc8a0e",
  "#775dff",
  "#aa17e6",
  "#149bda",
  "#4f4b51"
  ]
brights = [
  "#a7a5a8",
  "#d8137f",
  "#17ad98",
  "#dc8a0e",
  "#775dff",
  "#aa17e6",
  "#149bda",
  "#322d34"
  ]
