# Base16 Windows High Contrast Light - wezterm color config
# Scheme by Fergus Collins (https://github.com/ferguscollins)
[colors]
background = "#fcfcfc"
foreground = "#545454"

cursor_bg = "#545454"
cursor_border = "#545454"
cursor_fg = "#fcfcfc"

selection_bg = "#545454"
selection_fg = "#fcfcfc"

ansi = [
  "#fcfcfc",
  "#800000",
  "#008000",
  "#808000",
  "#000080",
  "#800080",
  "#008080",
  "#2a2a2a"
  ]
brights = [
  "#c0c0c0",
  "#800000",
  "#008000",
  "#808000",
  "#000080",
  "#800080",
  "#008080",
  "#000000"
  ]

[colors.indexed]
16 = "#fcfc54"
17 = "#54fc54"
18 = "#e8e8e8"
19 = "#d4d4d4"
20 = "#7e7e7e"
21 = "#545454"
