# Base16 Tokyo City Terminal Dark - wezterm color config
# Scheme by Michaël Ball
[colors]
background = "#171d23"
foreground = "#d8e2ec"

cursor_bg = "#1d252c"
cursor_border = "#d8e2ec"
cursor_fg = "#f6f6f8"

selection_bg = "#d8e2ec"
selection_fg = "#171d23"

ansi = [
  "#171d23",
  "#d95468",
  "#8bd49c",
  "#ebbf83",
  "#539afc",
  "#b62d65",
  "#70e1e8",
  "#f6f6f8"
  ]
brights = [
  "#526270",
  "#d95468",
  "#8bd49c",
  "#ebbf83",
  "#539afc",
  "#b62d65",
  "#70e1e8",
  "#fbfbfd"
  ]
