# Base16 Grayscale Dark - wezterm color config
# Scheme by Alexandre Gavioli (https://github.com/Alexx2/)
[colors]
background = "#101010"
foreground = "#b9b9b9"

cursor_bg = "#252525"
cursor_border = "#b9b9b9"
cursor_fg = "#e3e3e3"

selection_bg = "#b9b9b9"
selection_fg = "#101010"

ansi = [
  "#101010",
  "#7c7c7c",
  "#8e8e8e",
  "#a0a0a0",
  "#686868",
  "#747474",
  "#868686",
  "#e3e3e3"
  ]
brights = [
  "#525252",
  "#7c7c7c",
  "#8e8e8e",
  "#a0a0a0",
  "#686868",
  "#747474",
  "#868686",
  "#f7f7f7"
  ]
