# Base16 Github - wezterm color config
# Scheme by Tinted Theming (https://github.com/tinted-theming)
[colors]
background = "#eaeef2"
foreground = "#424a53"

cursor_bg = "#424a53"
cursor_border = "#424a53"
cursor_fg = "#eaeef2"

selection_bg = "#424a53"
selection_fg = "#eaeef2"

ansi = [
  "#eaeef2",
  "#fa4549",
  "#2da44e",
  "#bf8700",
  "#218bff",
  "#a475f9",
  "#339d9b",
  "#32383f"
  ]
brights = [
  "#8c959f",
  "#fa4549",
  "#2da44e",
  "#bf8700",
  "#218bff",
  "#a475f9",
  "#339d9b",
  "#1f2328"
  ]

[colors.indexed]
16 = "#e16f24"
17 = "#4d2d00"
18 = "#d0d7de"
19 = "#afb8c1"
20 = "#6e7781"
21 = "#424a53"
