# Base16 Apathy - wezterm color config
# Scheme by Jannik Siebert (https://github.com/janniks)
[colors]
background = "#031a16"
foreground = "#81b5ac"

cursor_bg = "#81b5ac"
cursor_border = "#81b5ac"
cursor_fg = "#031a16"

selection_bg = "#81b5ac"
selection_fg = "#031a16"

ansi = [
  "#031a16",
  "#3e9688",
  "#883e96",
  "#3e4c96",
  "#96883e",
  "#4c963e",
  "#963e4c",
  "#a7cec8"
  ]
brights = [
  "#2b685e",
  "#3e9688",
  "#883e96",
  "#3e4c96",
  "#96883e",
  "#4c963e",
  "#963e4c",
  "#d2e7e4"
  ]
