# Base16 Oxocarbon Light - wezterm color config
# Scheme by shaunsingh/IBM
[colors]
background = "#f2f4f8"
foreground = "#393939"

cursor_bg = "#dde1e6"
cursor_border = "#393939"
cursor_fg = "#525252"

selection_bg = "#393939"
selection_fg = "#f2f4f8"

ansi = [
  "#f2f4f8",
  "#ff7eb6",
  "#0f62fe",
  "#ff6f00",
  "#42be65",
  "#be95ff",
  "#673ab7",
  "#525252"
  ]
brights = [
  "#161616",
  "#ff7eb6",
  "#0f62fe",
  "#ff6f00",
  "#42be65",
  "#be95ff",
  "#673ab7",
  "#08bdba"
  ]
