# Base16 Ayu Mirage - wezterm color config
# Scheme by Khue Nguyen &lt;Z5483Y@gmail.com&gt;
[colors]
background = "#171b24"
foreground = "#cccac2"

cursor_bg = "#cccac2"
cursor_border = "#cccac2"
cursor_fg = "#171b24"

selection_bg = "#cccac2"
selection_fg = "#171b24"

ansi = [
  "#171b24",
  "#f28779",
  "#d5ff80",
  "#ffd173",
  "#5ccfe6",
  "#d4bfff",
  "#95e6cb",
  "#d9d7ce"
  ]
brights = [
  "#707a8c",
  "#f28779",
  "#d5ff80",
  "#ffd173",
  "#5ccfe6",
  "#d4bfff",
  "#95e6cb",
  "#f3f4f5"
  ]

[colors.indexed]
16 = "#ffad66"
17 = "#f29e74"
18 = "#1f2430"
19 = "#242936"
20 = "#8a9199"
21 = "#cccac2"
