# Base16 Apprentice - wezterm color config
# Scheme by romainl
[colors]
background = "#262626"
foreground = "#5f5f87"

cursor_bg = "#5f5f87"
cursor_border = "#5f5f87"
cursor_fg = "#262626"

selection_bg = "#5f5f87"
selection_fg = "#262626"

ansi = [
  "#262626",
  "#444444",
  "#ffffaf",
  "#87af87",
  "#8787af",
  "#5fafaf",
  "#87afd7",
  "#5f8787"
  ]
brights = [
  "#87875f",
  "#444444",
  "#ffffaf",
  "#87af87",
  "#8787af",
  "#5fafaf",
  "#87afd7",
  "#6c6c6c"
  ]
