# Base16 Horizon Terminal Light - wezterm color config
# Scheme by Michaël Ball (http://github.com/michael-ball/)
[colors]
background = "#fdf0ed"
foreground = "#403c3d"

cursor_bg = "#403c3d"
cursor_border = "#403c3d"
cursor_fg = "#fdf0ed"

selection_bg = "#403c3d"
selection_fg = "#fdf0ed"

ansi = [
  "#fdf0ed",
  "#e95678",
  "#29d398",
  "#fadad1",
  "#26bbd9",
  "#ee64ac",
  "#59e1e3",
  "#302c2d"
  ]
brights = [
  "#bdb3b1",
  "#e95678",
  "#29d398",
  "#fadad1",
  "#26bbd9",
  "#ee64ac",
  "#59e1e3",
  "#201c1d"
  ]
