# Base16 Everforest Dark Soft - wezterm color config
# Scheme by Sainnhe Park (https://github.com/sainnhe)
[colors]
background = "#333c43"
foreground = "#d3c6aa"

cursor_bg = "#3a464c"
cursor_border = "#d3c6aa"
cursor_fg = "#ddd8be"

selection_bg = "#d3c6aa"
selection_fg = "#333c43"

ansi = [
  "#333c43",
  "#e67e80",
  "#a7c080",
  "#dbbc7f",
  "#7fbbb3",
  "#d699b6",
  "#83c092",
  "#ddd8be"
  ]
brights = [
  "#859289",
  "#e67e80",
  "#a7c080",
  "#dbbc7f",
  "#7fbbb3",
  "#d699b6",
  "#83c092",
  "#f3ead3"
  ]
