# Base16 Grayscale Light - wezterm color config
# Scheme by Alexandre Gavioli (https://github.com/Alexx2/)
[colors]
background = "#f7f7f7"
foreground = "#464646"

cursor_bg = "#e3e3e3"
cursor_border = "#464646"
cursor_fg = "#252525"

selection_bg = "#464646"
selection_fg = "#f7f7f7"

ansi = [
  "#f7f7f7",
  "#7c7c7c",
  "#8e8e8e",
  "#a0a0a0",
  "#686868",
  "#747474",
  "#868686",
  "#252525"
  ]
brights = [
  "#ababab",
  "#7c7c7c",
  "#8e8e8e",
  "#a0a0a0",
  "#686868",
  "#747474",
  "#868686",
  "#101010"
  ]

[colors.indexed]
16 = "#999999"
17 = "#5e5e5e"
18 = "#e3e3e3"
19 = "#b9b9b9"
20 = "#525252"
21 = "#464646"
