# Base16 OneDark Dark - wezterm color config
# Scheme by olimorris (https://github.com/olimorris)
[colors]
background = "#000000"
foreground = "#abb2bf"

cursor_bg = "#1c1f24"
cursor_border = "#abb2bf"
cursor_fg = "#b6bdca"

selection_bg = "#abb2bf"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#ef596f",
  "#89ca78",
  "#e5c07b",
  "#61afef",
  "#d55fde",
  "#2bbac5",
  "#b6bdca"
  ]
brights = [
  "#434852",
  "#ef596f",
  "#89ca78",
  "#e5c07b",
  "#61afef",
  "#d55fde",
  "#2bbac5",
  "#c8ccd4"
  ]
