# Base16 Google Dark - wezterm color config
# Scheme by Seth Wright (http://sethawright.com)
[colors]
background = "#1d1f21"
foreground = "#c5c8c6"

cursor_bg = "#c5c8c6"
cursor_border = "#c5c8c6"
cursor_fg = "#1d1f21"

selection_bg = "#c5c8c6"
selection_fg = "#1d1f21"

ansi = [
  "#1d1f21",
  "#cc342b",
  "#198844",
  "#fba922",
  "#3971ed",
  "#a36ac7",
  "#3971ed",
  "#e0e0e0"
  ]
brights = [
  "#969896",
  "#cc342b",
  "#198844",
  "#fba922",
  "#3971ed",
  "#a36ac7",
  "#3971ed",
  "#ffffff"
  ]

[colors.indexed]
16 = "#f96a38"
17 = "#3971ed"
18 = "#282a2e"
19 = "#373b41"
20 = "#b4b7b4"
21 = "#c5c8c6"
