# tinted8 Github Dark
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#0d1117"
foreground = "#f0f6fc"

cursor_bg = "#f0f6fc"
cursor_border = "#f0f6fc"
cursor_fg = "#0d1117"

selection_bg = "#656c76"
selection_fg = "#f0f6fc"

ansi = [
  "#2f3742",
  "#ff7b72",
  "#3fb950",
  "#d29922",
  "#58a6ff",
  "#be8fff",
  "#39c5cf",
  "#f0f6fc"
]
brights = [
  "#656c76",
  "#ffa198",
  "#56d364",
  "#e3b341",
  "#79c0ff",
  "#d2a8ff",
  "#56d4dd",
  "#ffffff"
]

