# tinted8 Github Light High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-termihal)

[colors]
background = "#ffffff"
foreground = "#010409"

cursor_bg = "#010409"
cursor_border = "#010409"
cursor_fg = "#ffffff"

selection_bg = "#3d454c"
selection_fg = "#010409"

ansi = [
  "#010409",
  "#a0111f",
  "#024c1a",
  "#3f2200",
  "#0349b4",
  "#622cbc",
  "#1b7c83",
  "#59636e"
]
brights = [
  "#393f46",
  "#86061d",
  "#055d20",
  "#4e2c00",
  "#1168e3",
  "#844ae7",
  "#3192aa",
  "#818b98"
]

