# Rio Terminal base24 color theme (https://github.com/tinted-theming)
# Color scheme: Github Light High Contrast by Tinted Theming (https://github.com/tinted-theming)

[colors]
selection-background = '#454c54' # base05
selection-foreground = '#d1d9e0' # base02

cursor         = '#454c54' # base05
tabs           = '#f6f8fa' # base01
tabs-active    = '#d1d9e0' # base02

background     = '#ffffff' # base00
foreground     = '#454c54' # base05
black          = '#ffffff' # base00
red            = '#a0111f' # base08
yellow         = '#603700' # base0A
green          = '#024c1a' # base0B
cyan           = '#1b7c83' # base0C
blue           = '#0349b4' # base0D
magenta        = '#622cbc' # base0E
white          = '#454c54' # base05

dim-foreground   = '#454c54' # base05
dim-black        = '#f6f8fa' # base01
dim-red          = '#a0111f' # base08
dim-yellow       = '#603700' # base0A
dim-green        = '#024c1a' # base0B
dim-cyan         = '#1b7c83' # base0C
dim-blue         = '#0349b4' # base0D
dim-magenta      = '#622cbc' # base0E
dim-white        = '#59636e' # base04

light-foreground = '#454c54' # base05
light-black      = '#818b98' # base03
light-red        = '#86061d' # base12
light-yellow     = '#4e2c00' # base13
light-green      = '#055d20' # base14
light-cyan       = '#3192aa' # base15
light-blue       = '#1168e3' # base16
light-magenta    = '#844ae7' # base17
light-white      = '#010409' # base07
