# Rio Terminal base24 color theme (https://github.com/tinted-theming)
# Color scheme: Github Light by Tinted Theming (https://github.com/tinted-theming)

[colors]
selection-background = '#454c54' # base05
selection-foreground = '#d1d9e0' # base02

cursor         = '#454c54' # base05
tabs           = '#f6f8fa' # base01
tabs-active    = '#d1d9e0' # base02

background     = '#ffffff' # base00
foreground     = '#454c54' # base05
black          = '#ffffff' # base00
red            = '#cf222e' # base08
yellow         = '#9a6700' # base0A
green          = '#116329' # base0B
cyan           = '#1b7c83' # base0C
blue           = '#0969da' # base0D
magenta        = '#8250df' # base0E
white          = '#454c54' # base05

dim-foreground   = '#454c54' # base05
dim-black        = '#f6f8fa' # base01
dim-red          = '#cf222e' # base08
dim-yellow       = '#9a6700' # base0A
dim-green        = '#116329' # base0B
dim-cyan         = '#1b7c83' # base0C
dim-blue         = '#0969da' # base0D
dim-magenta      = '#8250df' # base0E
dim-white        = '#59636e' # base04

light-foreground = '#454c54' # base05
light-black      = '#818b98' # base03
light-red        = '#a40e26' # base12
light-yellow     = '#633c01' # base13
light-green      = '#1a7f37' # base14
light-cyan       = '#3192aa' # base15
light-blue       = '#218bff' # base16
light-magenta    = '#a475f9' # base17
light-white      = '#1f2328' # base07
