# Rio Terminal tinted8 color theme (https://github.com/tinted-theming)
# Color scheme: Github Dark by 

[colors]
selection-background = '#656c76'
selection-foreground = '#f0f6fc'

cursor         = '#f0f6fc'
tabs           = '#656c76'
tabs-active    = '#484e55'

background     = '#0d1117'
foreground     = '#f0f6fc'
black          = '#2f3742'
red            = '#ff7b72'
yellow         = '#d29922'
green          = '#3fb950'
cyan           = '#39c5cf'
blue           = '#58a6ff'
magenta        = '#be8fff'
white          = '#f0f6fc'

dim-foreground   = '#bad7f4'
dim-black        = '#15191e'
dim-red          = '#ff4235'
dim-yellow       = '#a27415'
dim-green        = '#2c8f3a'
dim-cyan         = '#239fa8'
dim-blue         = '#1b85ff'
dim-magenta      = '#9a52ff'
dim-white        = '#bad7f4'

light-foreground = '#ffffff'
light-black      = '#656c76'
light-red        = '#ffa198'
light-yellow     = '#e3b341'
light-green      = '#56d364'
light-cyan       = '#56d4dd'
light-blue       = '#79c0ff'
light-magenta    = '#d2a8ff'
light-white      = '#ffffff'
