# Scheme name: Sequoia Monochrome Light
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-sequoia-monochrome-light
ColorForeground=#282930
ColorBackground=#edeef2
ColorCursor=#282930
ColorBoldIsBright=FALSE
ColorPalette=#edeef2;#525666;#2e3038;#50535e;#5f6370;#50535e;#454752;#282930;#9da2ad;#525666;#2e3038;#50535e;#5f6370;#50535e;#454752;#0f1014
