# Scheme name: Serendipity Midnight
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-serendipity-midnight
ColorForeground=#dee0ef
ColorBackground=#151726
ColorCursor=#dee0ef
ColorBoldIsBright=FALSE
ColorPalette=#151726;#ee8679;#5ba2d0;#a78bfa;#94b8ff;#a78bfa;#f8d2c9;#dee0ef;#6b6d7c;#ee8679;#5ba2d0;#a78bfa;#94b8ff;#a78bfa;#f8d2c9;#151726
