# Scheme name: Sequoia Retro Dark
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-sequoia-retro-dark
ColorForeground=#868690
ColorBackground=#0f1014
ColorCursor=#868690
ColorBoldIsBright=FALSE
ColorPalette=#0f1014;#829fa7;#648f68;#da674b;#5c87a4;#da674b;#a27e57;#868690;#43444d;#829fa7;#648f68;#da674b;#5c87a4;#da674b;#a27e57;#0f1014
