# Scheme name: Corduroy Dark
# Scheme author: taysatte (https://github.com/taysatte)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-corduroy-dark
ColorForeground=#ddd8df
ColorBackground=#141016
ColorCursor=#ddd8df
ColorBoldIsBright=FALSE
ColorPalette=#141016;#e8758a;#55a0a0;#f0bd9c;#dc92a3;#cf98c4;#f0a89b;#ddd8df;#7d7082;#e8758a;#55a0a0;#f0bd9c;#dc92a3;#cf98c4;#f0a89b;#5a5160
