# Scheme name: Github Dark High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-github-dark-high-contrast
ColorForeground=#d1d7e0
ColorBackground=#0d1117
ColorCursor=#d1d7e0
ColorBoldIsBright=FALSE
ColorPalette=#0d1117;#ff9492;#28d751;#f0b72f;#71b7ff;#cb9eff;#39c5cf;#d1d7e0;#656c76;#ffb1af;#4ae168;#f7c843;#91cbff;#dbb7ff;#56d4dd;#ffffff
