# Scheme name: Oslo
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-oslo
ColorForeground=#abb2bf
ColorBackground=#3f4451
ColorCursor=#abb2bf
ColorBoldIsBright=FALSE
ColorPalette=#3f4451;#e05561;#8cc265;#d18f52;#4aa5f0;#c162de;#42b3c2;#abb2bf;#6c727f;#e05561;#8cc265;#d18f52;#4aa5f0;#c162de;#42b3c2;#ffffff
