# Scheme name: Github Dark
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-github-dark
ColorForeground=#d1d7e0
ColorBackground=#0d1117
ColorCursor=#d1d7e0
ColorBoldIsBright=FALSE
ColorPalette=#0d1117;#ff7b72;#3fb950;#d29922;#58a6ff;#be8fff;#39c5cf;#d1d7e0;#656c76;#ffa198;#56d364;#e3b341;#79c0ff;#d2a8ff;#56d4dd;#ffffff
