# Scheme name: Bogota
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-bogota
ColorForeground=#f7f1ff
ColorBackground=#200b0a
ColorCursor=#f7f1ff
ColorBoldIsBright=FALSE
ColorPalette=#200b0a;#fc618d;#7bd88f;#ffed89;#47e6ff;#ff9999;#47e6ff;#f7f1ff;#525053;#fc618d;#7bd88f;#ffed89;#47e6ff;#ff9999;#47e6ff;#f7f1ff
