# Scheme name: Praha
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-praha
ColorForeground=#ffffff
ColorBackground=#1a1a1a
ColorCursor=#ffffff
ColorBoldIsBright=FALSE
ColorPalette=#1a1a1a;#ff5555;#b8e6a0;#ffe4a3;#bd93f9;#ff9aa2;#8be9fd;#ffffff;#6272a4;#ff5555;#b8e6a0;#ffe4a3;#bd93f9;#ff9aa2;#8be9fd;#ffffff
