# Scheme name: Eldritch
# Scheme author: https://github.com/eldritch-theme
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-eldritch
ColorForeground=#ebfafa
ColorBackground=#212337
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#323449;#f16c75;#37f499;#f1fc79;#39ddfd;#a48cf2;#04d1f9;#f0f2f4;#3b4261;#f89a9d;#6fffc1;#f5ffa1;#f0313e;#f58bc8;#6ce9ff;#ffffff
