# Scheme name: Github Light High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-github-light-high-contrast
ColorForeground=#454c54
ColorBackground=#ffffff
ColorCursor=#454c54
ColorBoldIsBright=FALSE
ColorPalette=#ffffff;#a0111f;#024c1a;#603700;#0349b4;#622cbc;#1b7c83;#454c54;#818b98;#a0111f;#024c1a;#603700;#0349b4;#622cbc;#1b7c83;#010409
