# Scheme name: Sequoia Moonlight Dark
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-sequoia-moonlight-dark
ColorForeground=#868690
ColorBackground=#0f1014
ColorCursor=#868690
ColorBoldIsBright=FALSE
ColorPalette=#0f1014;#f58ee0;#8eb6f5;#9898a6;#c58fff;#9898a6;#ffbb88;#868690;#43444d;#f58ee0;#8eb6f5;#9898a6;#c58fff;#9898a6;#ffbb88;#0f1014
