# Scheme name: Github Dark Colorblind
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-github-dark-colorblind
ColorForeground=#d1d7e0
ColorBackground=#0d1117
ColorCursor=#d1d7e0
ColorBoldIsBright=FALSE
ColorPalette=#0d1117;#f0883e;#58a6ff;#d29922;#58a6ff;#be8fff;#39c5cf;#d1d7e0;#656c76;#f0883e;#58a6ff;#d29922;#58a6ff;#be8fff;#39c5cf;#ffffff
