# Scheme name: Abyssal
# Scheme author: Joss Wright (https://www.weirddatascience.net)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-abyssal
ColorForeground=#e0e4e7
ColorBackground=#000000
ColorCursor=#e0e4e7
ColorBoldIsBright=FALSE
ColorPalette=#000000;#ff7518;#39aa62;#ffcc00;#01a0e4;#ab5ccb;#40e0d0;#e0e4e7;#4f5b66;#feac57;#4ce070;#ffee50;#4b97c8;#ba8efa;#20b2aa;#f7f7ff
