# Scheme name: Miami
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-miami
ColorForeground=#f7f1ff
ColorBackground=#000000
ColorCursor=#f7f1ff
ColorBoldIsBright=FALSE
ColorPalette=#000000;#ff4c8b;#7fffd4;#ffd84c;#00ffa8;#d36cff;#47cfff;#f7f1ff;#69676c;#ff4c8b;#7fffd4;#ffd84c;#00ffa8;#d36cff;#47cfff;#f7f1ff
