# Scheme name: Helsinki
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-helsinki
ColorForeground=#544d40
ColorBackground=#f8fafe
ColorCursor=#544d40
ColorBoldIsBright=FALSE
ColorPalette=#f8fafe;#1faa9e;#733d9a;#2e70ad;#b55a0f;#3e9d21;#bd4c3d;#544d40;#b0a999;#1faa9e;#733d9a;#2e70ad;#b55a0f;#3e9d21;#bd4c3d;#000000
