# Scheme name: Github Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-github-light
ColorForeground=#454c54
ColorBackground=#ffffff
ColorCursor=#454c54
ColorBoldIsBright=FALSE
ColorPalette=#ffffff;#cf222e;#116329;#9a6700;#0969da;#8250df;#1b7c83;#454c54;#818b98;#a40e26;#1a7f37;#633c01;#218bff;#a475f9;#3192aa;#1f2328
