# Scheme name: Github Dark Dimmed
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-github-dark-dimmed
ColorForeground=#d1d7e0
ColorBackground=#0d1117
ColorCursor=#d1d7e0
ColorBoldIsBright=FALSE
ColorPalette=#0d1117;#f47067;#57ab5a;#c69026;#539bf5;#b083f0;#39c5cf;#d1d7e0;#656c76;#f47067;#57ab5a;#c69026;#539bf5;#b083f0;#39c5cf;#cdd9e5
