# Scheme name: Sequoia Retro Light
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-sequoia-retro-light
ColorForeground=#282930
ColorBackground=#edeef2
ColorCursor=#282930
ColorBoldIsBright=FALSE
ColorPalette=#edeef2;#5f7982;#4a704e;#bf5238;#456a82;#bf5238;#8a6539;#282930;#565760;#5f7982;#4a704e;#bf5238;#456a82;#bf5238;#8a6539;#0f1014
