# Scheme name: Ayu Light
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-ayu-light
ColorForeground=#cbcbcb
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#ff3333;#86b300;#73d8ff;#41a6d9;#f07178;#4dbf99;#ffffff;#323232;#ff6565;#b8e532;#ffc94a;#73d8ff;#ffa3aa;#7ff1cb;#ffffff
