# Scheme name: Github Light Colorblind
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-github-light-colorblind
ColorForeground=#454c54
ColorBackground=#ffffff
ColorCursor=#454c54
ColorBoldIsBright=FALSE
ColorPalette=#ffffff;#bc4c00;#0550ae;#9a6700;#0969da;#8250df;#1b7c83;#454c54;#818b98;#bc4c00;#0550ae;#9a6700;#0969da;#8250df;#1b7c83;#1f2328
