# Scheme name: Github Dark Colorblind
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=tinted8-github-dark-colorblind
ColorForeground=#f0f6fc
ColorBackground=#0d1117
ColorCursor=#f0f6fc
ColorBoldIsBright=FALSE
ColorPalette=#2f3742;#f0883e;#58a6ff;#d29922;#58a6ff;#be8fff;#39c5cf;#f0f6fc;#656c76;#ffa657;#79c0ff;#e3b341;#79c0ff;#d2a8ff;#56d4dd;#ffffff

