# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Apathy (legacy)
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-apathy-legacy
ColorForeground=#81b5ac
ColorBackground=#031a16
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0b342d;#3e9688;#883e96;#3e4c96;#96883e;#4c963e;#963e4c;#a7cec8;#184e45;#3e7996;#0b342d;#184e45;#5f9c92;#a7cec8;#3e965b;#d2e7e4
