# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Pico (legacy)
# Scheme author: PICO-8 (http://www.lexaloffle.com/pico-8.php)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-pico-legacy
ColorForeground=#5f574f
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d2b53;#ff004d;#00e756;#fff024;#83769c;#ff77a8;#29adff;#c2c3c7;#7e2553;#ffa300;#1d2b53;#7e2553;#ab5236;#c2c3c7;#ffccaa;#fff1e8
