# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Embers Light (legacy)
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-embers-light-legacy
ColorForeground=#323b43
ColorBackground=#d1d6db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#aeb6be;#576d82;#6d8257;#57826d;#82576d;#6d5782;#826d57;#20262c;#909aa3;#578282;#aeb6be;#909aa3;#47505a;#20262c;#575782;#0f1316
