# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Material Lighter (legacy)
# Scheme author: Nate Peterson
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-material-lighter-legacy
ColorForeground=#80cbc4
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e7eaec;#ff5370;#91b859;#ffb62c;#6182b8;#7c4dff;#39adb5;#80cbc4;#cceae7;#f76d47;#e7eaec;#cceae7;#8796b0;#80cbc4;#e53935;#ffffff
