# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Materia (legacy)
# Scheme author: Defman21
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-materia-legacy
ColorForeground=#cdd3de
ColorBackground=#263238
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2c393f;#ec5f67;#8bd649;#ffcc00;#89ddff;#82aaff;#80cbc4;#d5dbe5;#37474f;#ea9560;#2c393f;#37474f;#c9ccd3;#d5dbe5;#ec5f67;#ffffff
