# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Evenok Dark (legacy)
# Scheme author: Mekeor Melire
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-evenok-dark-legacy
ColorForeground=#d0d0d0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202020;#f5708a;#54bc5c;#b8a300;#00aff2;#9095ff;#00bab3;#e0e0e0;#303030;#ee8122;#202020;#303030;#b0b0b0;#e0e0e0;#d47ada;#ffffff
