# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Isotope (legacy)
# Scheme author: Jan T. Sott
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-isotope-legacy
ColorForeground=#d0d0d0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#404040;#ff0000;#33ff00;#ff0099;#0066ff;#cc00ff;#00ffff;#e0e0e0;#606060;#ff9900;#404040;#606060;#c0c0c0;#e0e0e0;#3300ff;#ffffff
