# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Flat (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-flat-legacy
ColorForeground=#e0e0e0
ColorBackground=#2c3e50
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#34495e;#e74c3c;#2ecc71;#f1c40f;#3498db;#9b59b6;#1abc9c;#f5f5f5;#7f8c8d;#e67e22;#34495e;#7f8c8d;#bdc3c7;#f5f5f5;#be643c;#ecf0f1
