# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Railscasts (legacy)
# Scheme author: Ryan Bates (http://railscasts.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-railscasts-legacy
ColorForeground=#e6e1dc
ColorBackground=#2b2b2b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#272935;#da4939;#a5c261;#ffc66d;#6d9cbe;#b6b3eb;#519f50;#f4f1ed;#3a4055;#cc7833;#272935;#3a4055;#d4cfc9;#f4f1ed;#bc9458;#f9f7f3
