# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Primer Dark (legacy)
# Scheme author: Jimmy Lin
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-primer-dark-legacy
ColorForeground=#b1bac4
ColorBackground=#010409
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#21262d;#ff7b72;#3fb950;#d29922;#58a6ff;#f778ba;#a5d6ff;#c9d1d9;#30363d;#f0883e;#21262d;#30363d;#8b949e;#c9d1d9;#bd561d;#f0f6fc
