# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Windows 95 (legacy)
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-windows-95-legacy
ColorForeground=#a8a8a8
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1c1c;#fc5454;#54fc54;#fcfc54;#5454fc;#fc54fc;#54fcfc;#d2d2d2;#383838;#a85400;#1c1c1c;#383838;#7e7e7e;#d2d2d2;#00a800;#fcfcfc
