# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo City Light (legacy)
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-city-light-legacy
ColorForeground=#343b59
ColorBackground=#fbfbfd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f6f6f8;#8c4351;#485e30;#4c505e;#34548a;#5a4a78;#4c505e;#1d252c;#edeff6;#965027;#f6f6f8;#edeff6;#4c505e;#1d252c;#5a4a78;#171d23
