# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Oxocarbon Dark (legacy)
# Scheme author: shaunsingh/IBM
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-oxocarbon-dark-legacy
ColorForeground=#f2f4f8
ColorBackground=#161616
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#262626;#3ddbd9;#33b1ff;#ee5396;#42be65;#be95ff;#ff7eb6;#ffffff;#393939;#78a9ff;#262626;#393939;#dde1e6;#ffffff;#82cfff;#08bdba
