# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Material Palenight (legacy)
# Scheme author: Nate Peterson
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-material-palenight-legacy
ColorForeground=#959dcb
ColorBackground=#292d3e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#444267;#f07178;#c3e88d;#ffcb6b;#82aaff;#c792ea;#89ddff;#959dcb;#32374d;#f78c6c;#444267;#32374d;#8796b0;#959dcb;#ff5370;#ffffff
