# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: iA Light (legacy)
# Scheme author: iA Inc. (modified by aramisgithub)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-ia-light-legacy
ColorForeground=#181818
ColorBackground=#f6f6f6
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dedede;#9c5a02;#38781c;#c48218;#48bac2;#a94598;#2d6bb1;#e8e8e8;#bde5f2;#c43e18;#dedede;#bde5f2;#767676;#e8e8e8;#8b6c37;#f8f8f8
