# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Jabuti (legacy)
# Scheme author: https://github.com/notusknot
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-jabuti-legacy
ColorForeground=#c0cbe3
ColorBackground=#292a37
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#343545;#ec6a88;#3fdaa4;#e1c697;#3fc6de;#be95ff;#ff7eb6;#d9e0ee;#3c3e51;#efb993;#343545;#3c3e51;#50526b;#d9e0ee;#8b8da9;#ffffff
