# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Gotham (legacy)
# Scheme author: Andrea Leopardi (arranged by Brett Jones)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-gotham-legacy
ColorForeground=#599cab
ColorBackground=#0c1014
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#11151c;#c23127;#33859e;#edb443;#195466;#888ca6;#2aa889;#99d1ce;#091f2e;#d26937;#11151c;#091f2e;#245361;#99d1ce;#4e5166;#d3ebe9
