# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Edge Light (legacy)
# Scheme author: cjayross (https://github.com/cjayross)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-edge-light-legacy
ColorForeground=#5e646f
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#7c9f4b;#db7070;#7c9f4b;#d69822;#6587bf;#b870ce;#509c93;#b870ce;#d69822;#db7070;#7c9f4b;#d69822;#6587bf;#b870ce;#509c93;#5e646f
