# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Classic Dark (legacy)
# Scheme author: Jason Heeris (http://heeris.id.au)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-classic-dark-legacy
ColorForeground=#d0d0d0
ColorBackground=#151515
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202020;#ac4142;#90a959;#f4bf75;#6a9fb5;#aa759f;#75b5aa;#e0e0e0;#303030;#d28445;#202020;#303030;#b0b0b0;#e0e0e0;#8f5536;#f5f5f5
