# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: summercamp (legacy)
# Scheme author: zoe firi (zoefiri.github.io)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-summercamp-legacy
ColorForeground=#736e55
ColorBackground=#1c1810
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a261c;#e35142;#5ceb5a;#f2ff27;#489bf0;#ff8080;#5aebbc;#bab696;#3a3527;#fba11b;#2a261c;#3a3527;#5f5b45;#bab696;#f69be7;#f8f5de
