# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Bespin (legacy)
# Scheme author: Jan T. Sott
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-bespin-legacy
ColorForeground=#8a8986
ColorBackground=#28211c
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#36312e;#cf6a4c;#54be0d;#f9ee98;#5ea6ea;#9b859d;#afc4db;#9d9b97;#5e5d5c;#cf7d34;#36312e;#5e5d5c;#797977;#9d9b97;#937121;#baae9e
