# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: London Tube (legacy)
# Scheme author: Jan T. Sott
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tube-legacy
ColorForeground=#d9d8d8
ColorBackground=#231f20
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c3f95;#ee2e24;#00853e;#ffd204;#009ddc;#98005d;#85cebc;#e7e7e8;#5a5758;#f386a1;#1c3f95;#5a5758;#959ca1;#e7e7e8;#b06110;#ffffff
