# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Zenburn (legacy)
# Scheme author: elnawe
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-zenburn-legacy
ColorForeground=#dcdccc
ColorBackground=#383838
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#404040;#dca3a3;#5f7f5f;#e0cf9f;#7cb8bb;#dc8cc3;#93e0e3;#c0c0c0;#606060;#dfaf8f;#404040;#606060;#808080;#c0c0c0;#000000;#ffffff
