# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Material Darker (legacy)
# Scheme author: Nate Peterson
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-material-darker-legacy
ColorForeground=#eeffff
ColorBackground=#212121
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303030;#f07178;#c3e88d;#ffcb6b;#82aaff;#c792ea;#89ddff;#eeffff;#353535;#f78c6c;#303030;#353535;#b2ccd6;#eeffff;#ff5370;#ffffff
