# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Unikitty Dark (legacy)
# Scheme author: Josh W Lewis (@joshwlewis)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-unikitty-dark-legacy
ColorForeground=#bcbabe
ColorBackground=#2e2a31
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#4a464d;#d8137f;#17ad98;#dc8a0e;#796af5;#bb60ea;#149bda;#d8d7da;#666369;#d65407;#4a464d;#666369;#9f9da2;#d8d7da;#c720ca;#f5f4f7
