# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: IR Black (legacy)
# Scheme author: Timothée Poisot (http://timotheepoisot.fr)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-irblack-legacy
ColorForeground=#b5b3aa
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#242422;#ff6c60;#a8ff60;#ffffb6;#96cbfe;#ff73fd;#c6c5fe;#d9d7cc;#484844;#e9c062;#242422;#484844;#918f88;#d9d7cc;#b18a3d;#fdfbee
