# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: vice (legacy)
# Scheme author: Thomas Leon Highbaugh thighbaugh@zoho.com
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-vice-legacy
ColorForeground=#8b9cbe
ColorBackground=#17191e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#22262d;#ff29a8;#0badff;#f0ffaa;#00eaff;#00f6d9;#8265ff;#b2bfd9;#3c3f4c;#85ffe0;#22262d;#3c3f4c;#555e70;#b2bfd9;#ff3d81;#f4f4f7
