# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Primer Dark Dimmed (legacy)
# Scheme author: Jimmy Lin
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-primer-dark-dimmed-legacy
ColorForeground=#909dab
ColorBackground=#1c2128
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#373e47;#f47067;#57ab5a;#c69026;#539bf5;#e275ad;#96d0ff;#adbac7;#444c56;#e0823d;#373e47;#444c56;#768390;#adbac7;#ae5622;#cdd9e5
