# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Brewer (legacy)
# Scheme author: Timothée Poisot (http://github.com/tpoisot)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-brewer-legacy
ColorForeground=#b7b8b9
ColorBackground=#0c0d0e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2e2f30;#e31a1c;#31a354;#dca060;#3182bd;#756bb1;#80b1d3;#dadbdc;#515253;#e6550d;#2e2f30;#515253;#959697;#dadbdc;#b15928;#fcfdfe
