# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Equilibrium Gray Light (legacy)
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-equilibrium-gray-light-legacy
ColorForeground=#474747
ColorBackground=#f1f1f1
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e2e2e2;#d02023;#637200;#9d6f00;#0073b5;#4e66b6;#007a72;#303030;#d4d4d4;#bf3e05;#e2e2e2;#d4d4d4;#5e5e5e;#303030;#c42775;#1b1b1b
