# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Stella (legacy)
# Scheme author: Shrimpram
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-stella-legacy
ColorForeground=#998bad
ColorBackground=#2b213c
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#362b48;#c79987;#acc79b;#c7c691;#a5aad4;#c594ff;#9bc7bf;#b4a5c8;#4d4160;#8865c6;#362b48;#4d4160;#7f7192;#b4a5c8;#c7ab87;#ebdcff
