# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Twilight (legacy)
# Scheme author: David Hart (https://github.com/hartbit)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-twilight-legacy
ColorForeground=#a7a7a7
ColorBackground=#1e1e1e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#323537;#cf6a4c;#8f9d6a;#f9ee98;#7587a6;#9b859d;#afc4db;#c3c3c3;#464b50;#cda869;#323537;#464b50;#838184;#c3c3c3;#9b703f;#ffffff
