# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Atlas (legacy)
# Scheme author: Alex Lende (https://ajlende.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-atlas-legacy
ColorForeground=#a1a19a
ColorBackground=#002635
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#00384d;#ff5a67;#7fc06e;#ffcc1b;#14747e;#9a70a4;#5dd7b9;#e6e6dc;#517f8d;#f08e48;#00384d;#517f8d;#869696;#e6e6dc;#c43060;#fafaf8
