# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo Night Moon (legacy)
# Scheme author: Ólafur Bjarki Bogason
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-night-moon-legacy
ColorForeground=#3b4261
ColorBackground=#222436
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1e2030;#ff757f;#c3e88d;#ffc777;#82aaff;#fca7ea;#86e1fc;#828bb8;#2d3f76;#ffc777;#1e2030;#2d3f76;#828bb8;#828bb8;#c53b53;#c8d3f5
