# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tomorrow (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tomorrow-legacy
ColorForeground=#4d4d4c
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e0e0e0;#c82829;#718c00;#eab700;#4271ae;#8959a8;#3e999f;#282a2e;#d6d6d6;#f5871f;#e0e0e0;#d6d6d6;#969896;#282a2e;#a3685a;#1d1f21
