# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: XCode Dusk (legacy)
# Scheme author: Elsa Gonsiorowski (https://github.com/gonsie)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-xcode-dusk-legacy
ColorForeground=#939599
ColorBackground=#282b35
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3d4048;#b21889;#df0002;#438288;#790ead;#b21889;#00a0be;#a9aaae;#53555d;#786dc5;#3d4048;#53555d;#7e8086;#a9aaae;#c77c48;#bebfc2
