# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Apprentice (legacy)
# Scheme author: romainl
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-apprentice-legacy
ColorForeground=#5f5f87
ColorBackground=#262626
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#af5f5f;#444444;#ffffaf;#87af87;#8787af;#5fafaf;#87afd7;#5f8787;#5f875f;#ff8700;#af5f5f;#5f875f;#5f87af;#5f8787;#bcbcbc;#6c6c6c
