# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Embers (legacy)
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-embers-legacy
ColorForeground=#a39a90
ColorBackground=#16130f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2c2620;#826d57;#57826d;#6d8257;#6d5782;#82576d;#576d82;#beb6ae;#433b32;#828257;#2c2620;#433b32;#8a8075;#beb6ae;#825757;#dbd6d1
