# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo Night Storm (legacy)
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-night-storm-legacy
ColorForeground=#a9b1d6
ColorBackground=#24283b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#16161e;#c0caf5;#9ece6a;#0db9d7;#2ac3de;#bb9af7;#b4f9f8;#cbccd1;#343a52;#a9b1d6;#16161e;#343a52;#787c99;#cbccd1;#f7768e;#d5d6db
