# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo Night Terminal Light (legacy)
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-night-terminal-light-legacy
ColorForeground=#4c505e
ColorBackground=#d5d6db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#cbccd1;#8c4351;#33635c;#8f5e15;#34548a;#5a4a78;#0f4b6e;#1a1b26;#dfe0e5;#965027;#cbccd1;#dfe0e5;#4c505e;#1a1b26;#655259;#1a1b26
