# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: darkmoss (legacy)
# Scheme author: Gabriel Avanzi (https://github.com/avanzzzi)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-darkmoss-legacy
ColorForeground=#c7c7a5
ColorBackground=#171e1f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#252c2d;#ff4658;#499180;#fdb11f;#498091;#9bc0c8;#66d9ef;#e3e3c8;#373c3d;#e6db74;#252c2d;#373c3d;#818f80;#e3e3c8;#d27b53;#e1eaef
