# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Primer Light (legacy)
# Scheme author: Jimmy Lin
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-primer-light-legacy
ColorForeground=#2f363d
ColorBackground=#fafbfc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e1e4e8;#d73a49;#28a745;#ffd33d;#0366d6;#ea4aaa;#79b8ff;#24292e;#d1d5da;#f66a0a;#e1e4e8;#d1d5da;#444d56;#24292e;#a04100;#1b1f23
