# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Google Dark (legacy)
# Scheme author: Seth Wright (http://sethawright.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-google-dark-legacy
ColorForeground=#c5c8c6
ColorBackground=#1d1f21
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282a2e;#cc342b;#198844;#fba922;#3971ed;#a36ac7;#3971ed;#e0e0e0;#373b41;#f96a38;#282a2e;#373b41;#b4b7b4;#e0e0e0;#3971ed;#ffffff
