# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Woodland (legacy)
# Scheme author: Jay Cornwall (https://jcornwall.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-woodland-legacy
ColorForeground=#cabcb1
ColorBackground=#231e18
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#302b25;#d35c5c;#b7ba53;#e0ac16;#88a4d3;#bb90e2;#6eb958;#d7c8bc;#48413a;#ca7f32;#302b25;#48413a;#b4a490;#d7c8bc;#b49368;#e4d4c8
