# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Atelier Cave (legacy)
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-atelier-cave-legacy
ColorForeground=#8b8792
ColorBackground=#19171c
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#26232a;#be4678;#2a9292;#a06e3b;#576ddb;#955ae7;#398bc6;#e2dfe7;#585260;#aa573c;#26232a;#585260;#7e7887;#e2dfe7;#bf40bf;#efecf4
