# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Material Vivid (legacy)
# Scheme author: joshyrobot
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-material-vivid-legacy
ColorForeground=#80868b
ColorBackground=#202124
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#27292c;#f44336;#00e676;#ffeb3b;#2196f3;#673ab7;#00bcd4;#9e9e9e;#323639;#ff9800;#27292c;#323639;#676c71;#9e9e9e;#8d6e63;#ffffff
