# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Unikitty Light (legacy)
# Scheme author: Josh W Lewis (@joshwlewis)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-unikitty-light-legacy
ColorForeground=#6c696e
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e1e1e2;#d8137f;#17ad98;#dc8a0e;#775dff;#aa17e6;#149bda;#4f4b51;#c4c3c5;#d65407;#e1e1e2;#c4c3c5;#89878b;#4f4b51;#e013d0;#322d34
