# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: SAGA (legacy)
# Scheme author: https://github.com/SAGAtheme/SAGA
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-saga-legacy
ColorForeground=#dce2f7
ColorBackground=#05080a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0a1014;#ffd4e9;#f7ddff;#fbebc8;#c9fff7;#dcc3f9;#c5edc1;#f8eae7;#0f181e;#fbcbae;#0a1014;#0f181e;#192630;#f8eae7;#f6dddd;#ccd3fe
