# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: eris (legacy)
# Scheme author: ed (https://codeberg.org/ed)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-eris-legacy
ColorForeground=#606bac
ColorBackground=#0a0920
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#13133a;#f768a3;#faaea2;#faaea2;#258fc4;#f768a3;#258fc4;#7986c5;#23255a;#f768a3;#13133a;#23255a;#4a5293;#7986c5;#f768a3;#9aaae5
