# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Nebula (legacy)
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-nebula-legacy
ColorForeground=#a4a6a9
ColorBackground=#22273b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#414f60;#777abc;#6562a8;#4f9062;#4d6bb6;#716cae;#226f68;#c7c9cd;#5a8380;#94929e;#414f60;#5a8380;#87888b;#c7c9cd;#8c70a7;#8dbdaa
