# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Material (legacy)
# Scheme author: Nate Peterson
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-material-legacy
ColorForeground=#eeffff
ColorBackground=#263238
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2e3c43;#f07178;#c3e88d;#ffcb6b;#82aaff;#c792ea;#89ddff;#eeffff;#314549;#f78c6c;#2e3c43;#314549;#b2ccd6;#eeffff;#ff5370;#ffffff
