# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: lime (legacy)
# Scheme author: limelier
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-lime-legacy
ColorForeground=#818175
ColorBackground=#1a1a2f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202030;#ff662a;#8cd97c;#ffd15e;#2b926f;#1b825f;#4cad83;#fff2d1;#2a2a3f;#ff773a;#202030;#2a2a3f;#515155;#fff2d1;#b4d97c;#fff8e1
