# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Windows NT (legacy)
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-windows-nt-legacy
ColorForeground=#c0c0c0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a2a2a;#ff0000;#00ff00;#ffff00;#0000ff;#ff00ff;#00ffff;#e0e0e0;#555555;#808000;#2a2a2a;#555555;#a1a1a1;#e0e0e0;#008000;#ffffff
