# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Fruit Soda (legacy)
# Scheme author: jozip
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-fruit-soda-legacy
ColorForeground=#515151
ColorBackground=#f1ecf1
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e0dee0;#fe3e31;#47f74c;#f7e203;#2931df;#611fce;#0f9cfd;#474545;#d8d5d5;#fe6d08;#e0dee0;#d8d5d5;#979598;#474545;#b16f40;#2d2c2c
