# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Gigavolt (legacy)
# Scheme author: Aidan Swope (http://github.com/Whillikers)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-gigavolt-legacy
ColorForeground=#e9e7e1
ColorBackground=#202126
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2d303d;#ff661a;#f2e6a9;#ffdc2d;#40bfff;#ae94f9;#fb6acb;#eff0f9;#5a576e;#19f988;#2d303d;#5a576e;#cad3ff;#eff0f9;#6187ff;#f2fbff
