# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Sparky (legacy)
# Scheme author: Leila Sother (https://github.com/mixcoac)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-sparky-legacy
ColorForeground=#f4f5f0
ColorBackground=#072b31
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#00313c;#ff585d;#78d64b;#fbdd40;#4698cb;#d59ed7;#2dccd3;#f5f5f1;#003c46;#ff8f1c;#00313c;#003c46;#00778b;#f5f5f1;#9b704d;#ffffff
