# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Paraiso (legacy)
# Scheme author: Jan T. Sott
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-paraiso-legacy
ColorForeground=#a39e9b
ColorBackground=#2f1e2e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#41323f;#ef6155;#48b685;#fec418;#06b6ef;#815ba4;#5bc4bf;#b9b6b0;#4f424c;#f99b15;#41323f;#4f424c;#8d8687;#b9b6b0;#e96ba8;#e7e9db
