# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Da One White (legacy)
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-da-one-white-legacy
ColorForeground=#181818
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#c8c8c8;#de5d6e;#76a85d;#b3684f;#5890f8;#c173d1;#64b5a7;#000000;#888888;#ff9470;#c8c8c8;#888888;#282828;#000000;#b3684f;#000000
