# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Github (legacy)
# Scheme author: Defman21
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-github-legacy
ColorForeground=#333333
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f5f5f5;#ed6a43;#183691;#795da3;#795da3;#a71d5d;#183691;#ffffff;#c8c8fa;#0086b3;#f5f5f5;#c8c8fa;#e8e8e8;#ffffff;#333333;#ffffff
