# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Default Dark (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-default-dark-legacy
ColorForeground=#d8d8d8
ColorBackground=#181818
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282828;#ab4642;#a1b56c;#f7ca88;#7cafc2;#ba8baf;#86c1b9;#e8e8e8;#383838;#dc9656;#282828;#383838;#b8b8b8;#e8e8e8;#a16946;#f8f8f8
