# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Helios (legacy)
# Scheme author: Alex Meyer (https://github.com/reyemxela)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-helios-legacy
ColorForeground=#d5d5d5
ColorBackground=#1d2021
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#383c3e;#d72638;#88b92d;#f19d1a;#1e8bac;#be4264;#1ba595;#dddddd;#53585b;#eb8413;#383c3e;#53585b;#cdcdcd;#dddddd;#c85e0d;#e5e5e5
