# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tango (legacy)
# Scheme author: @Schnouki, based on the Tango Desktop Project
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tango-legacy
ColorForeground=#d3d7cf
ColorBackground=#2e3436
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#8ae234;#cc0000;#4e9a06;#c4a000;#3465a4;#75507b;#06989a;#ad7fa8;#fce94f;#ef2929;#8ae234;#fce94f;#729fcf;#ad7fa8;#34e2e2;#eeeeec
