# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Codeschool (legacy)
# Scheme author: blockloop
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-codeschool-legacy
ColorForeground=#9ea7a6
ColorBackground=#232c31
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c3657;#2a5491;#237986;#a03b1e;#484d79;#c59820;#b02f30;#a7cfa3;#2a343a;#43820d;#1c3657;#2a343a;#84898c;#a7cfa3;#c98344;#b5d8f6
