# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Pop (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-pop-legacy
ColorForeground=#d0d0d0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202020;#eb008a;#37b349;#f8ca12;#0e5a94;#b31e8d;#00aabb;#e0e0e0;#303030;#f29333;#202020;#303030;#b0b0b0;#e0e0e0;#7a2d00;#ffffff
