# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Darcula (legacy)
# Scheme author: jetbrains
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-darcula-legacy
ColorForeground=#a9b7c6
ColorBackground=#2b2b2b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#323232;#4eade5;#6a8759;#bbb529;#9876aa;#cc7832;#629755;#ffc66d;#323232;#689757;#323232;#323232;#a4a3a3;#ffc66d;#808080;#ffffff
