# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Kimber (legacy)
# Scheme author: Mishka Nguyen (https://github.com/akhsiM)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-kimber-legacy
ColorForeground=#dedee7
ColorBackground=#222222
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#313131;#c88c8c;#99c899;#d8b56d;#537c9c;#86cacd;#78b4b4;#c3c3b4;#555d55;#476c88;#313131;#555d55;#5a5a5a;#c3c3b4;#704f4f;#ffffe6
