# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Windows 10 (legacy)
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-windows-10-legacy
ColorForeground=#cccccc
ColorBackground=#0c0c0c
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2f2f2f;#e74856;#16c60c;#f9f1a5;#3b78ff;#b4009e;#61d6d6;#dfdfdf;#535353;#c19c00;#2f2f2f;#535353;#b9b9b9;#dfdfdf;#13a10e;#f2f2f2
