# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Pasque (legacy)
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-pasque-legacy
ColorForeground=#dedcdf
ColorBackground=#271c3a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#100323;#a92258;#c6914b;#804ead;#8e7dc6;#953b9d;#7263aa;#edeaef;#3e2d5c;#918889;#100323;#3e2d5c;#bebcbf;#edeaef;#59325c;#bbaadd
