# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: tarot (legacy)
# Scheme author: ed (https://codeberg.org/ed)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tarot-legacy
ColorForeground=#aa556f
ColorBackground=#0e091d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a153c;#c53253;#a68e5a;#ff6565;#6e6080;#a45782;#8c9785;#c4686d;#4b2054;#ea4d60;#2a153c;#4b2054;#8c406f;#c4686d;#984d51;#dc8f7c
