# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Ayu Light (legacy)
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-ayu-light-legacy
ColorForeground=#5c6773
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f3f4f5;#f07178;#86b300;#f2ae49;#36a3d9;#a37acc;#4cbf99;#242936;#f8f9fa;#fa8d3e;#f3f4f5;#f8f9fa;#828c99;#242936;#e6ba7e;#1a1f29
