# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: vulcan (legacy)
# Scheme author: Andrey Varfolomeev
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-vulcan-legacy
ColorForeground=#5b778c
ColorBackground=#041523
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#122339;#818591;#977d7c;#adb4b9;#977d7c;#9198a3;#977d7c;#333238;#003552;#9198a3;#122339;#003552;#6b6977;#333238;#977d7c;#214d68
