# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Hopscotch (legacy)
# Scheme author: Jan T. Sott
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-hopscotch-legacy
ColorForeground=#b9b5b8
ColorBackground=#322931
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#433b42;#dd464c;#8fc13e;#fdcc59;#1290bf;#c85e7c;#149b93;#d5d3d5;#5c545b;#fd8b19;#433b42;#5c545b;#989498;#d5d3d5;#b33508;#ffffff
