# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo City Dark (legacy)
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-city-dark-legacy
ColorForeground=#d8e2ec
ColorBackground=#171d23
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d252c;#f7768e;#9ece6a;#b7c5d3;#7aa2f7;#bb9af7;#89ddff;#f6f6f8;#28323a;#ff9e64;#1d252c;#28323a;#b7c5d3;#f6f6f8;#bb9af7;#fbfbfd
