# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Equilibrium Gray Dark (legacy)
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-equilibrium-gray-dark-legacy
ColorForeground=#ababab
ColorBackground=#111111
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1b1b1b;#f04339;#7f8b00;#bb8801;#008dd1;#6a7fd2;#00948b;#c6c6c6;#262626;#df5923;#1b1b1b;#262626;#919191;#c6c6c6;#e3488e;#e2e2e2
