# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Rosé Pine Moon (legacy)
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-rose-pine-moon-legacy
ColorForeground=#e0def4
ColorBackground=#232136
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a273f;#eb6f92;#3e8fb0;#ea9a97;#c4a7e7;#f6c177;#9ccfd8;#e0def4;#393552;#f6c177;#2a273f;#393552;#908caa;#e0def4;#56526e;#56526e
