# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Ocean (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-ocean-legacy
ColorForeground=#c0c5ce
ColorBackground=#2b303b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#343d46;#bf616a;#a3be8c;#ebcb8b;#8fa1b3;#b48ead;#96b5b4;#dfe1e8;#4f5b66;#d08770;#343d46;#4f5b66;#a7adba;#dfe1e8;#ab7967;#eff1f5
