# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Rosé Pine (legacy)
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-rose-pine-legacy
ColorForeground=#e0def4
ColorBackground=#191724
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1f1d2e;#eb6f92;#31748f;#ebbcba;#c4a7e7;#f6c177;#9ccfd8;#e0def4;#26233a;#f6c177;#1f1d2e;#26233a;#908caa;#e0def4;#524f67;#524f67
