# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Oxocarbon Light (legacy)
# Scheme author: shaunsingh/IBM
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-oxocarbon-light-legacy
ColorForeground=#393939
ColorBackground=#f2f4f8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dde1e6;#ff7eb6;#0f62fe;#ff6f00;#42be65;#be95ff;#673ab7;#525252;#525252;#ee5396;#dde1e6;#525252;#262626;#525252;#37474f;#08bdba
