# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Bright (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-bright-legacy
ColorForeground=#e0e0e0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303030;#fb0120;#a1c659;#fda331;#6fb3d2;#d381c3;#76c7b7;#f5f5f5;#505050;#fc6d24;#303030;#505050;#d0d0d0;#f5f5f5;#be643c;#ffffff
