# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Mocha (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-mocha-legacy
ColorForeground=#d0c8c6
ColorBackground=#3b3228
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#534636;#cb6077;#beb55b;#f4bc87;#8ab3b5;#a89bb9;#7bbda4;#e9e1dd;#645240;#d28b71;#534636;#645240;#b8afad;#e9e1dd;#bb9584;#f5eeeb
