# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Still Alive (legacy)
# Scheme author: Derrick McKee (derrick.mckee@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-still-alive-legacy
ColorForeground=#d80000
ColorBackground=#f0f0f0
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f0d848;#487830;#5c5c6a;#426395;#001878;#900000;#2c3c57;#489000;#fff018;#183048;#f0d848;#fff018;#f00000;#489000;#140c0d;#30a860
