# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: One Light (legacy)
# Scheme author: Daniel Pfeifer (http://github.com/purpleKarrot)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-one-light-legacy
ColorForeground=#383a42
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f0f0f1;#ca1243;#50a14f;#c18401;#4078f2;#a626a4;#0184bc;#202227;#e5e5e6;#d75f00;#f0f0f1;#e5e5e6;#696c77;#202227;#986801;#090a0b
