# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Equilibrium Light (legacy)
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-equilibrium-light-legacy
ColorForeground=#43474e
ColorBackground=#f5f0e7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e7e2d9;#d02023;#637200;#9d6f00;#0073b5;#4e66b6;#007a72;#2c3138;#d8d4cb;#bf3e05;#e7e2d9;#d8d4cb;#5a5f66;#2c3138;#c42775;#181c22
