# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Humanoid light (legacy)
# Scheme author: Thomas (tasmo) Friese
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-humanoid-light-legacy
ColorForeground=#232629
ColorBackground=#f8f8f2
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#efefe9;#b0151a;#388e3c;#ffb627;#0082c9;#700f98;#008e8e;#2f3337;#deded8;#ff3d00;#efefe9;#deded8;#60615d;#2f3337;#b27701;#070708
