# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Unikitty Reversible (legacy)
# Scheme author: Josh W Lewis (@joshwlewis)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-unikitty-reversible-legacy
ColorForeground=#c3c2c4
ColorBackground=#2e2a31
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#4b484e;#d8137f;#17ad98;#dc8a0e;#7864fa;#b33ce8;#149bda;#e1e0e1;#69666b;#d65407;#4b484e;#69666b;#a5a3a6;#e1e0e1;#d41acd;#ffffff
