# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Icy Dark (legacy)
# Scheme author: icyphox (https://icyphox.ga)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-icy-legacy
ColorForeground=#095b67
ColorBackground=#021012
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#031619;#16c1d9;#4dd0e1;#80deea;#00bcd4;#00acc1;#26c6da;#0c7c8c;#041f23;#b3ebf2;#031619;#041f23;#064048;#0c7c8c;#0097a7;#109cb0
