# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Nord (legacy)
# Scheme author: arcticicestudio
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-nord-legacy
ColorForeground=#e5e9f0
ColorBackground=#2e3440
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3b4252;#bf616a;#a3be8c;#ebcb8b;#81a1c1;#b48ead;#88c0d0;#eceff4;#434c5e;#d08770;#3b4252;#434c5e;#d8dee9;#eceff4;#5e81ac;#8fbcbb
