# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Humanoid dark (legacy)
# Scheme author: Thomas (tasmo) Friese
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-humanoid-dark-legacy
ColorForeground=#f8f8f2
ColorBackground=#232629
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#333b3d;#f11235;#02d849;#ffb627;#00a6fb;#f15ee3;#0dd9d6;#fcfcf6;#484e54;#ff9505;#333b3d;#484e54;#c0c0bd;#fcfcf6;#b27701;#fcfcfc
