# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Purpledream (legacy)
# Scheme author: malet
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-purpledream-legacy
ColorForeground=#ddd0dd
ColorBackground=#100510
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#302030;#ff1d0d;#14cc64;#f000a0;#00a0f0;#b000d0;#0075b0;#eee0ee;#403040;#ccae14;#302030;#403040;#bbb0bb;#eee0ee;#6a2a3c;#fff0ff
