# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Katy (legacy)
# Scheme author: George Essig (https://github.com/gessig)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-katy-legacy
ColorForeground=#959dcb
ColorBackground=#292d3e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#444267;#6e98e1;#78c06e;#e0a557;#82aaff;#c792ea;#83b7e5;#959dcb;#5c598b;#f78c6c;#444267;#5c598b;#8796b0;#959dcb;#ff5370;#ffffff
