# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Seti UI (legacy)
# Scheme author: 
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-seti-legacy
ColorForeground=#d6d6d6
ColorBackground=#151718
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282a2b;#cd3f45;#9fca56;#e6cd69;#55b5db;#a074c4;#55dbbe;#eeeeee;#3b758c;#db7b55;#282a2b;#3b758c;#43a5d5;#eeeeee;#8a553f;#ffffff
