# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tomorrow Night (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tomorrow-night-legacy
ColorForeground=#c5c8c6
ColorBackground=#1d1f21
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282a2e;#cc6666;#b5bd68;#f0c674;#81a2be;#b294bb;#8abeb7;#e0e0e0;#373b41;#de935f;#282a2e;#373b41;#b4b7b4;#e0e0e0;#a3685a;#ffffff
