# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo City Terminal Dark (legacy)
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-city-terminal-dark-legacy
ColorForeground=#d8e2ec
ColorBackground=#171d23
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d252c;#d95468;#8bd49c;#ebbf83;#539afc;#b62d65;#70e1e8;#f6f6f8;#28323a;#ff9e64;#1d252c;#28323a;#b7c5d3;#f6f6f8;#dd9d82;#fbfbfd
