# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Default Light (legacy)
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-default-light-legacy
ColorForeground=#383838
ColorBackground=#f8f8f8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e8e8e8;#ab4642;#a1b56c;#f7ca88;#7cafc2;#ba8baf;#86c1b9;#282828;#d8d8d8;#dc9656;#e8e8e8;#d8d8d8;#585858;#282828;#a16946;#181818
