# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Edge Dark (legacy)
# Scheme author: cjayross (https://github.com/cjayross)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-edge-dark-legacy
ColorForeground=#b7bec9
ColorBackground=#262729
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#88909f;#e77171;#a1bf78;#dbb774;#73b3e7;#d390e7;#5ebaa5;#d390e7;#b7bec9;#e77171;#88909f;#b7bec9;#73b3e7;#d390e7;#5ebaa5;#3e4249
