# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Eva (legacy)
# Scheme author: kjakapat (https://github.com/kjakapat)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-eva-legacy
ColorForeground=#9fa2a6
ColorBackground=#2a3b4d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3d566f;#c4676c;#66ff66;#ffff66;#15f4ee;#9c6cd3;#4b8f77;#d6d7d9;#4b6988;#ff9966;#3d566f;#4b6988;#7e90a3;#d6d7d9;#bb64a9;#ffffff
