# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Ashes (legacy)
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-ashes-legacy
ColorForeground=#c7ccd1
ColorBackground=#1c2023
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#393f45;#c7ae95;#95c7ae;#aec795;#ae95c7;#c795ae;#95aec7;#dfe2e5;#565e65;#c7c795;#393f45;#565e65;#adb3ba;#dfe2e5;#c79595;#f3f4f5
