# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Zenbones (legacy)
# Scheme author: mcchrish
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-zenbones-legacy
ColorForeground=#b279a7
ColorBackground=#191919
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#de6e7c;#3d3839;#d68c67;#8bae68;#cf86c1;#65b8c1;#61abda;#66a5ad;#819b69;#e8838f;#de6e7c;#819b69;#6099c0;#66a5ad;#8e8e8e;#bbbbbb
