# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Heetch Light (legacy)
# Scheme author: Geoffrey Teale (tealeg@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-heetch-light-legacy
ColorForeground=#5a496e
ColorBackground=#feffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#392551;#27d9d5;#f80059;#5ba2b6;#47f9f5;#bd0152;#c33678;#470546;#7b6d8b;#bdb6c5;#392551;#7b6d8b;#ddd6e5;#470546;#dedae2;#190134
