# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: dirtysea (legacy)
# Scheme author: Kahlil (Kal) Hodgson
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-dirtysea-legacy
ColorForeground=#000000
ColorBackground=#e0e0e0
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#d0dad0;#840000;#730073;#755b00;#007300;#000090;#755b00;#f8f8f8;#d0d0d0;#006565;#d0dad0;#d0d0d0;#202020;#f8f8f8;#755b00;#c4d9c4
