# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Equilibrium Dark (legacy)
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-equilibrium-dark-legacy
ColorForeground=#afaba2
ColorBackground=#0c1118
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#181c22;#f04339;#7f8b00;#bb8801;#008dd1;#6a7fd2;#00948b;#cac6bd;#22262d;#df5923;#181c22;#22262d;#949088;#cac6bd;#e3488e;#e7e2d9
