# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Hardcore (legacy)
# Scheme author: Chris Caller
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-hardcore-legacy
ColorForeground=#cdcdcd
ColorBackground=#212121
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303030;#f92672;#a6e22e;#e6db74;#66d9ef;#9e6ffe;#708387;#e5e5e5;#353535;#fd971f;#303030;#353535;#707070;#e5e5e5;#e8b882;#ffffff
