# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Moonlight (legacy)
# Scheme author: Jeremy Swinarton (https://github.com/jswinarton)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-moonlight-legacy
ColorForeground=#a3ace1
ColorBackground=#212337
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#403c64;#ff5370;#2df4c0;#ffc777;#40ffff;#b994f1;#04d1f9;#b4a4f4;#596399;#f67f81;#403c64;#596399;#a1abe0;#b4a4f4;#ecb2f0;#ef43fa
