# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Aztec (legacy)
# Scheme author: TheNeverMan (github.com/TheNeverMan)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-aztec-legacy
ColorForeground=#ffda51
ColorBackground=#101600
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a1e01;#ee2e00;#63d932;#eebb00;#5b4a9f;#883e9f;#3d94a5;#ffe178;#242604;#ee8800;#1a1e01;#242604;#ffd129;#ffe178;#a928b9;#ffeba0
