# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Decaf (legacy)
# Scheme author: Alex Mirrington (https://github.com/alexmirrington)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-decaf-legacy
ColorForeground=#cccccc
ColorBackground=#2d2d2d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#393939;#ff7f7b;#beda78;#ffd67c;#90bee1;#efb3f7;#bed6ff;#e0e0e0;#515151;#ffbf70;#393939;#515151;#b4b7b4;#e0e0e0;#ff93b3;#ffffff
