# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: pandora (legacy)
# Scheme author: Cassandra Fox
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-pandora-legacy
ColorForeground=#f15c99
ColorBackground=#131213
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2f1823;#b00b69;#9ddf69;#ffcc00;#008080;#a24030;#714ca6;#81506a;#472234;#ff9153;#2f1823;#472234;#9b2a46;#81506a;#a24030;#632227
