# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Silk Dark (legacy)
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-silk-dark-legacy
ColorForeground=#c7dbdd
ColorBackground=#0e3c46
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d494e;#fb6953;#73d8ad;#fce380;#46bddd;#756b8a;#3fb2b9;#cbf2f7;#2a5054;#fcab74;#1d494e;#2a5054;#9dc8cd;#cbf2f7;#9b647b;#d2faff
