# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Da One Ocean (legacy)
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-da-one-ocean-legacy
ColorForeground=#ffffff
ColorBackground=#171726
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#22273d;#fa7883;#98c379;#ff9470;#6bb8ff;#e799ff;#8af5ff;#ffffff;#525866;#ffc387;#22273d;#525866;#c8c8c8;#ffffff;#b3684f;#ffffff
