# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Macintosh (legacy)
# Scheme author: Rebecca Bettencourt (http://www.kreativekorp.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-macintosh-legacy
ColorForeground=#c0c0c0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#404040;#dd0907;#1fb714;#fbf305;#0000d3;#4700a5;#02abea;#c0c0c0;#404040;#ff6403;#404040;#404040;#808080;#c0c0c0;#90713a;#ffffff
