# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Colors (legacy)
# Scheme author: mrmrs (http://clrs.cc)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-colors-legacy
ColorForeground=#bbbbbb
ColorBackground=#111111
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#333333;#ff4136;#2ecc40;#ffdc00;#0074d9;#b10dc9;#7fdbff;#dddddd;#555555;#ff851b;#333333;#555555;#999999;#dddddd;#85144b;#ffffff
