# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Mellow Purple (legacy)
# Scheme author: gidsi
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-mellow-purple-legacy
ColorForeground=#ffeeff
ColorBackground=#1e0528
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a092d;#00d9e9;#05cb0d;#955ae7;#550068;#8991bb;#b900b1;#ffeeff;#331354;#aa00a3;#1a092d;#331354;#873582;#ffeeff;#4d6fff;#f8c0ff
