# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Da One Sea (legacy)
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-da-one-sea-legacy
ColorForeground=#ffffff
ColorBackground=#22273d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#374059;#fa7883;#98c379;#ff9470;#6bb8ff;#e799ff;#8af5ff;#ffffff;#525866;#ffc387;#374059;#525866;#c8c8c8;#ffffff;#b3684f;#ffffff
