# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo Night Light (legacy)
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-night-light-legacy
ColorForeground=#343b59
ColorBackground=#d5d6db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#cbccd1;#343b58;#485e30;#166775;#34548a;#5a4a78;#3e6968;#1a1b26;#dfe0e5;#965027;#cbccd1;#dfe0e5;#4c505e;#1a1b26;#8c4351;#1a1b26
