# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: emil (legacy)
# Scheme author: limelier
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-emil-legacy
ColorForeground=#313145
ColorBackground=#efefef
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#bebed2;#f43979;#0073a8;#ff669b;#471397;#6916b6;#2155d6;#22223a;#9e9eaf;#d22a8b;#bebed2;#9e9eaf;#505063;#22223a;#8d17a5;#1a1a2f
