# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Da One Black (legacy)
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-da-one-black-legacy
ColorForeground=#ffffff
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282828;#fa7883;#98c379;#ff9470;#6bb8ff;#e799ff;#8af5ff;#ffffff;#585858;#ffc387;#282828;#585858;#c8c8c8;#ffffff;#b3684f;#ffffff
