# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Brogrammer (legacy)
# Scheme author: Vik Ramanujam (http://github.com/piggyslasher)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-brogrammer-legacy
ColorForeground=#4e5ab7
ColorBackground=#1f1f1f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f81118;#d6dbe5;#f3bd09;#1dd361;#5350b9;#0f7ddb;#1081d6;#1081d6;#2dc55e;#de352e;#f81118;#2dc55e;#2a84d2;#1081d6;#ffffff;#d6dbe5
