# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Sandcastle (legacy)
# Scheme author: George Essig (https://github.com/gessig)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-sandcastle-legacy
ColorForeground=#a89984
ColorBackground=#282c34
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2c323b;#83a598;#528b8b;#a07e3b;#83a598;#d75f5f;#83a598;#d5c4a1;#3e4451;#a07e3b;#2c323b;#3e4451;#928374;#d5c4a1;#a87322;#fdf4c1
