# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Kanagawa (legacy)
# Scheme author: Tommaso Laurenzi (https://github.com/rebelot)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-kanagawa-legacy
ColorForeground=#dcd7ba
ColorBackground=#1f1f28
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#16161d;#c34043;#76946a;#c0a36e;#7e9cd8;#957fb8;#6a9589;#c8c093;#223249;#ffa066;#16161d;#223249;#727169;#c8c093;#d27e99;#717c7c
