# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Darktooth (legacy)
# Scheme author: Jason Milkins (https://github.com/jasonm23)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-darktooth-legacy
ColorForeground=#a89984
ColorBackground=#1d2021
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#32302f;#fb543f;#95c085;#fac03b;#0d6678;#8f4673;#8ba59b;#d5c4a1;#504945;#fe8625;#32302f;#504945;#928374;#d5c4a1;#a87322;#fdf4c1
