# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Solar Flare (legacy)
# Scheme author: Chuck Harmston (https://chuck.harmston.ch)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-solarflare-legacy
ColorForeground=#a6afb8
ColorBackground=#18262f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#222e38;#ef5253;#7cc844;#e4b51c;#33b5e1;#a363d5;#52cbb0;#e8e9ed;#586875;#e66b2b;#222e38;#586875;#85939e;#e8e9ed;#d73c9a;#f5f7fa
