# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Vesper (legacy)
# Scheme author: FormalSnake (https://github.com/formalsnake)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-vesper-legacy
ColorForeground=#b7b7b7
ColorBackground=#101010
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#232323;#de6e6e;#5f8787;#ffc799;#8eaaaa;#d69094;#60a592;#c1c1c1;#222222;#dab083;#232323;#222222;#999999;#c1c1c1;#876c4f;#d5d5d5
