# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: pinky (legacy)
# Scheme author: Benjamin (https://github.com/b3nj5m1n)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-pinky-legacy
ColorForeground=#f5f5f5
ColorBackground=#171517
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1b181b;#ffa600;#ff0066;#20df6c;#00ffff;#007fff;#6600ff;#ffffff;#1d1b1d;#00ff66;#1b181b;#1d1b1d;#e7dbdb;#ffffff;#df206c;#f7f3f7
