# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Silk Light (legacy)
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-silk-light-legacy
ColorForeground=#385156
ColorBackground=#e9f1ef
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ccd4d3;#cf432e;#6ca38c;#cfad25;#39aac9;#6e6582;#329ca2;#0e3c46;#90b7b6;#d27f46;#ccd4d3;#90b7b6;#4b5b5f;#0e3c46;#865369;#d2faff
