# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo Night Terminal Dark (legacy)
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-tokyo-night-terminal-dark-legacy
ColorForeground=#787c99
ColorBackground=#16161e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a1b26;#f7768e;#41a6b5;#e0af68;#7aa2f7;#bb9af7;#7dcfff;#cbccd1;#2f3549;#ff9e64;#1a1b26;#2f3549;#787c99;#cbccd1;#d18616;#d5d6db
