# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Mountain (legacy)
# Scheme author: gnsfujiwara (https://github.com/gnsfujiwara)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-mountain-legacy
ColorForeground=#cacaca
ColorBackground=#0f0f0f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#191919;#ac8a8c;#8aac8b;#aca98a;#8f8aac;#ac8aac;#8aabac;#e7e7e7;#262626;#ceb188;#191919;#262626;#ac8a8c;#e7e7e7;#ac8a8c;#f0f0f0
