# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Ayu Mirage (legacy)
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-ayu-mirage-legacy
ColorForeground=#cccac2
ColorBackground=#171b24
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1f2430;#f28779;#d5ff80;#ffd173;#5ccfe6;#d4bfff;#95e6cb;#d9d7ce;#242936;#ffad66;#1f2430;#242936;#8a9199;#d9d7ce;#f29e74;#f3f4f5
