# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: DanQing (legacy)
# Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-danqing-legacy
ColorForeground=#e0f0ef
ColorBackground=#2d302f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#434846;#f9906f;#8ab361;#f0c239;#b0a4e3;#cca4e3;#30dff3;#ecf6f2;#5a605d;#b38a61;#434846;#5a605d;#cad8d2;#ecf6f2;#ca6924;#fcfefd
