# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Shapeshifter (legacy)
# Scheme author: Tyler Benziger (http://tybenz.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-shapeshifter-legacy
ColorForeground=#102015
ColorBackground=#f9f9f9
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e0e0e0;#e92f2f;#0ed839;#dddd13;#3b48e3;#f996e2;#23edda;#040404;#ababab;#e09448;#e0e0e0;#ababab;#343434;#040404;#69542d;#000000
