# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Measured Light (legacy)
# Scheme author: Measured (https://measured.co)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-measured-light-legacy
ColorForeground=#292929
ColorBackground=#fdf9f5
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f9f5f1;#ac1f35;#0c680c;#645a00;#0158ad;#6645c2;#01716f;#181818;#ffeada;#ad5601;#f9f5f1;#ffeada;#404040;#181818;#a81a66;#000000
