# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Blue Forest (legacy)
# Scheme author: alonsodomin (https://github.com/alonsodomin)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-blueforest-legacy
ColorForeground=#ffcc33
ColorBackground=#141f2e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1e5c1e;#fffab1;#80ff80;#91ccff;#a2cff5;#0099ff;#80ff80;#91ccff;#273e5c;#ff8080;#1e5c1e;#273e5c;#1e5c1e;#91ccff;#e7e7e7;#375780
