# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: PhD (legacy)
# Scheme author: Hennig Hasemann (http://leetless.de/vim.html)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-phd-legacy
ColorForeground=#b8bbc2
ColorBackground=#061229
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a3448;#d07346;#99bf52;#fbd461;#5299bf;#9989cc;#72b9bf;#dbdde0;#4d5666;#f0a000;#2a3448;#4d5666;#9a99a3;#dbdde0;#b08060;#ffffff
