# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Atelier Dune (legacy)
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-atelier-dune-legacy
ColorForeground=#a6a28c
ColorBackground=#20201d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#292824;#d73737;#60ac39;#ae9513;#6684e1;#b854d4;#1fad83;#e8e4cf;#6e6b5e;#b65611;#292824;#6e6b5e;#999580;#e8e4cf;#d43552;#fefbec
