# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Heetch Dark (legacy)
# Scheme author: Geoffrey Teale (tealeg@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-heetch-legacy
ColorForeground=#bdb6c5
ColorBackground=#190134
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#392551;#27d9d5;#c33678;#8f6c97;#bd0152;#82034c;#f80059;#dedae2;#5a496e;#5ba2b6;#392551;#5a496e;#9c92a8;#dedae2;#470546;#feffff
