# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Sakura (legacy)
# Scheme author: Misterio77 (http://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-sakura-legacy
ColorForeground=#564448
ColorBackground=#feedf3
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f8e2e7;#df2d52;#2e916d;#c29461;#006e93;#5e2180;#1d8991;#42383a;#e0ccd1;#f6661e;#f8e2e7;#e0ccd1;#665055;#42383a;#ba0d35;#33292b
