# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: Framer (legacy)
# Scheme author: Framer (Maintained by Jesse Hoyos)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-framer-legacy
ColorForeground=#d0d0d0
ColorBackground=#181818
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#151515;#fd886b;#32ccdc;#fecb6e;#20bcfc;#ba8cfc;#acddfd;#e8e8e8;#464646;#fc4769;#151515;#464646;#b9b9b9;#e8e8e8;#b15f4a;#eeeeee
