# xfce4 Terminal Theme
# Scheme system: base16
# Scheme name: OneDark (legacy)
# Scheme author: Lalit Magant (http://github.com/tilal6991)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)
[Scheme]
Name=base16-onedark-legacy
ColorForeground=#abb2bf
ColorBackground=#282c34
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#353b45;#e06c75;#98c379;#e5c07b;#61afef;#c678dd;#56b6c2;#b6bdca;#3e4451;#d19a66;#353b45;#3e4451;#565c64;#b6bdca;#be5046;#c8ccd4
