# tinted-foot
# Scheme name: Miami
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=dark

[colors-dark]
foreground=f7f1ff
background=000000
regular0=000000 # black
regular1=ff4c8b # red
regular2=7fffd4 # green
regular3=ffd84c # yellow
regular4=00ffa8 # blue
regular5=d36cff # magenta
regular6=47cfff # cyan
regular7=f7f1ff # white
bright0=69676c # bright black
bright1=ff4c8b # bright red
bright2=7fffd4 # bright green
bright3=ffd84c # bright yellow
bright4=00ffa8 # bright blue
bright5=d36cff # bright magenta
bright6=47cfff # bright cyan
bright7=f7f1ff # bright white
16=ff926c
17=a65f46
18=111112
19=1e1d1f
20=88858c
21=f9f4ff
