# tinted-foot
# Scheme name: Serendipity Midnight
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=dark

[colors-dark]
foreground=dee0ef
background=151726
regular0=151726 # black
regular1=ee8679 # red
regular2=5ba2d0 # green
regular3=a78bfa # yellow
regular4=94b8ff # blue
regular5=a78bfa # magenta
regular6=f8d2c9 # cyan
regular7=dee0ef # white
bright0=6b6d7c # bright black
bright1=ee8679 # bright red
bright2=5ba2d0 # bright green
bright3=a78bfa # bright yellow
bright4=94b8ff # bright blue
bright5=a78bfa # bright magenta
bright6=f8d2c9 # bright cyan
bright7=151726 # bright white
16=ee8679
17=5ba2d0
18=1c1e2d
19=1c1e2d
20=8d8f9e
21=dee0ef
