# tinted-foot
# Scheme name: Sequoia Monochrome Dark
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=dark

[colors-dark]
foreground=868690
background=0f1014
regular0=0f1014 # black
regular1=999eb2 # red
regular2=626983 # green
regular3=d3d5de # yellow
regular4=7c829d # blue
regular5=d3d5de # magenta
regular6=b6bac8 # cyan
regular7=868690 # white
bright0=43444d # bright black
bright1=999eb2 # bright red
bright2=626983 # bright green
bright3=d3d5de # bright yellow
bright4=7c829d # bright blue
bright5=d3d5de # bright magenta
bright6=b6bac8 # bright cyan
bright7=0f1014 # bright white
16=999eb2
17=626983
18=111216
19=111216
20=575861
21=868690
