# tinted-foot
# Scheme name: Berlin
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=dark

[colors-dark]
foreground=cccccc
background=000000
regular0=000000 # black
regular1=999999 # red
regular2=bbbbbb # green
regular3=dddddd # yellow
regular4=888888 # blue
regular5=aaaaaa # magenta
regular6=cccccc # cyan
regular7=cccccc # white
bright0=333333 # bright black
bright1=bbbbbb # bright red
bright2=dddddd # bright green
bright3=ffffff # bright yellow
bright4=aaaaaa # bright blue
bright5=cccccc # bright magenta
bright6=eeeeee # bright cyan
bright7=ffffff # bright white
16=bbbbbb
17=7a7a7a
18=0e0e0e
19=181818
20=707070
21=d6d6d6
