# tinted-foot
# Scheme name: Helsinki
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=light

[colors-light]
foreground=544d40
background=f8fafe
regular0=f8fafe # black
regular1=1faa9e # red
regular2=733d9a # green
regular3=2e70ad # yellow
regular4=b55a0f # blue
regular5=3e9d21 # magenta
regular6=bd4c3d # cyan
regular7=544d40 # white
bright0=b0a999 # bright black
bright1=009e91 # bright red
bright2=5a1f8a # bright green
bright3=0f5ba2 # bright yellow
bright4=b23b00 # bright blue
bright5=218c00 # bright magenta
bright6=b32e1f # bright cyan
bright7=000000 # bright white
16=268da6
17=1b6374
18=edeef1
19=e4e5e7
20=8d8a82
21=3b362d
