# tinted-foot
# Scheme name: Abyssal
# Scheme author: Joss Wright (https://www.weirddatascience.net)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=dark

[colors-dark]
foreground=e0e4e7
background=000000
regular0=000000 # black
regular1=ff7518 # red
regular2=39aa62 # green
regular3=ffcc00 # yellow
regular4=01a0e4 # blue
regular5=ab5ccb # magenta
regular6=40e0d0 # cyan
regular7=e0e4e7 # white
bright0=4f5b66 # bright black
bright1=feac57 # bright red
bright2=4ce070 # bright green
bright3=ffee50 # bright yellow
bright4=4b97c8 # bright blue
bright5=ba8efa # bright magenta
bright6=20b2aa # bright cyan
bright7=f7f7ff # bright white
16=ff9f10
17=dd5500
18=1b2b34
19=343d46
20=65737e
21=e7e7f7
