# tinted-foot
# Scheme name: Serendipity Morning
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=light

[colors-light]
foreground=3f4363
background=f6f7fb
regular0=f6f7fb # black
regular1=c25a4d # red
regular2=2f7aab # green
regular3=785fd0 # yellow
regular4=6288d8 # blue
regular5=785fd0 # magenta
regular6=e58678 # cyan
regular7=3f4363 # white
bright0=6d7296 # bright black
bright1=c25a4d # bright red
bright2=2f7aab # bright green
bright3=785fd0 # bright yellow
bright4=6288d8 # bright blue
bright5=785fd0 # bright magenta
bright6=e58678 # bright cyan
bright7=f6f7fb # bright white
16=c25a4d
17=2f7aab
18=eaebee
19=eaebee
20=505575
21=3f4363
