# tinted-foot
# Scheme name: Apprentice
# Scheme author: Romain Lafourcade (https://github.com/romainl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=dark

[colors-dark]
foreground=bcbcbc
background=262626
regular0=262626 # black
regular1=af5f5f # red
regular2=5f875f # green
regular3=87875f # yellow
regular4=5f87af # blue
regular5=5f5f87 # magenta
regular6=5f8787 # cyan
regular7=bcbcbc # white
bright0=444444 # bright black
bright1=af5f5f # bright red
bright2=5f875f # bright green
bright3=87875f # bright yellow
bright4=5f87af # bright blue
bright5=5f5f87 # bright magenta
bright6=5f8787 # bright cyan
bright7=ffffff # bright white
16=ff8700
17=af5f5f
18=303030
19=3a3a3a
20=6c6c6c
21=dfdfdf
