# tinted-foot
# Scheme name: Madrid
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=light

[colors-light]
foreground=1a1a1a
background=fafafa
regular0=fafafa # black
regular1=990026 # red
regular2=007a28 # green
regular3=8a6408 # yellow
regular4=007a9e # blue
regular5=4d2699 # magenta
regular6=007a9e # cyan
regular7=1a1a1a # white
bright0=4d4d4d # bright black
bright1=990026 # bright red
bright2=007a28 # bright green
bright3=8a6408 # bright yellow
bright4=007a9e # bright blue
bright5=4d2699 # bright magenta
bright6=007a9e # bright cyan
bright7=1a1a1a # bright white
16=923217
17=662310
18=eaeaea
19=dfdfdf
20=686868
21=121212
