# tinted-foot
# Scheme name: Sequoia Monochrome Light
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming)

initial-color-theme=light

[colors-light]
foreground=282930
background=edeef2
regular0=edeef2 # black
regular1=525666 # red
regular2=2e3038 # green
regular3=50535e # yellow
regular4=5f6370 # blue
regular5=50535e # magenta
regular6=454752 # cyan
regular7=282930 # white
bright0=9da2ad # bright black
bright1=525666 # bright red
bright2=2e3038 # bright green
bright3=50535e # bright yellow
bright4=5f6370 # bright blue
bright5=50535e # bright magenta
bright6=454752 # bright cyan
bright7=0f1014 # bright white
16=525666
17=2e3038
18=e2e3e8
19=e2e3e8
20=42434e
21=282930
