# tinted-terminal - foot
# Scheme name: Github Light High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming)

[colors]
foreground=
background=
regular0=010409 # black
regular1=a0111f # red
regular2=024c1a # green
regular3=3f2200 # yellow
regular4=0349b4 # blue
regular5=622cbc # magenta
regular6=1b7c83 # cyan
regular7=59636e # white
bright0=393f46 # bright black
bright1=86061d # bright red
bright2=055d20 # bright green
bright3=4e2c00 # bright yellow
bright4=1168e3 # bright blue
bright5=844ae7 # bright magenta
bright6=3192aa # bright cyan
bright7=818b98 # bright white
