# tinted-terminal - foot
# Scheme name: Github Dark High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming)

[colors]
foreground=
background=
regular0=2f3742 # black
regular1=ff9492 # red
regular2=28d751 # green
regular3=f0b72f # yellow
regular4=71b7ff # blue
regular5=cb9eff # magenta
regular6=39c5cf # cyan
regular7=f0f6fc # white
bright0=656c76 # bright black
bright1=ffb1af # bright red
bright2=4ae168 # bright green
bright3=f7c843 # bright yellow
bright4=91cbff # bright blue
bright5=dbb7ff # bright magenta
bright6=56d4dd # bright cyan
bright7=ffffff # bright white
