# tinted-terminal - foot
# Scheme name: Github Dark Colorblind
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming)

[colors]
foreground=
background=
regular0=2f3742 # black
regular1=f0883e # red
regular2=58a6ff # green
regular3=d29922 # yellow
regular4=58a6ff # blue
regular5=be8fff # magenta
regular6=39c5cf # cyan
regular7=f0f6fc # white
bright0=656c76 # bright black
bright1=ffa657 # bright red
bright2=79c0ff # bright green
bright3=e3b341 # bright yellow
bright4=79c0ff # bright blue
bright5=d2a8ff # bright magenta
bright6=56d4dd # bright cyan
bright7=ffffff # bright white
