# Scheme name: Ayu Light
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-ayu-light
ColorForeground=#5c6773
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f3f4f5;#f07178;#86b300;#f2ae49;#36a3d9;#a37acc;#4cbf99;#242936;#f8f9fa;#f07178;#86b300;#f2ae49;#36a3d9;#a37acc;#4cbf99;#1a1f29
