# vim:ft=kitty

## name:     base16 X
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 X
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #050505
foreground #f7f1ff
selection_background #f7f1ff
selection_foreground #222123

# Cursor colors
cursor #f7f1ff
cursor_text_color #050505

# URL underline color when hovering with mouse
url_color #8a878e

# Kitty window border colors
active_border_color #6b686e
inactive_border_color #161616

# OS Window titlebar colors
wayland_titlebar_color #050505
macos_titlebar_color #050505

# Tab bar colors
active_tab_background #050505
active_tab_foreground #f7f1ff
inactive_tab_background #161616
inactive_tab_foreground #8a878e
tab_bar_background #161616

# The 16 terminal colors
# normal
color0 #050505
color1 #fc618d
color2 #7bd88f
color3 #fce566
color4 #fd9353
color5 #948ae3
color6 #5ad4e6
color7 #f7f1ff

# bright
color8 #6b686e
color9 #fc618d
color10 #7bd88f
color11 #fce566
color12 #fd9353
color13 #948ae3
color14 #5ad4e6
color15 #f7f1ff

# extended base16 colors
color16 #fca37a
color17 #a66c51
color18 #161616
color19 #222123
color20 #8a878e
color21 #f9f4ff
