# vim:ft=kitty

## name:     base16 Madrid
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 Madrid
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #fafafa
foreground #1a1a1a
selection_background #1a1a1a
selection_foreground #dfdfdf

# Cursor colors
cursor #1a1a1a
cursor_text_color #fafafa

# URL underline color when hovering with mouse
url_color #686868

# Kitty window border colors
active_border_color #4d4d4d
inactive_border_color #eaeaea

# OS Window titlebar colors
wayland_titlebar_color #fafafa
macos_titlebar_color #fafafa

# Tab bar colors
active_tab_background #fafafa
active_tab_foreground #1a1a1a
inactive_tab_background #eaeaea
inactive_tab_foreground #686868
tab_bar_background #eaeaea

# The 16 terminal colors
# normal
color0 #fafafa
color1 #990026
color2 #007a28
color3 #8a6408
color4 #007a9e
color5 #4d2699
color6 #007a9e
color7 #1a1a1a

# bright
color8 #4d4d4d
color9 #990026
color10 #007a28
color11 #8a6408
color12 #007a9e
color13 #4d2699
color14 #007a9e
color15 #1a1a1a

# extended base16 colors
color16 #923217
color17 #662310
color18 #eaeaea
color19 #dfdfdf
color20 #686868
color21 #121212
