# vim:ft=kitty

## name:     base16 Oslo
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 Oslo
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #3f4451
foreground #abb2bf
selection_background #abb2bf
selection_foreground #4c515e

# Cursor colors
cursor #abb2bf
cursor_text_color #3f4451

# URL underline color when hovering with mouse
url_color #7a808e

# Kitty window border colors
active_border_color #6c727f
inactive_border_color #474c59

# OS Window titlebar colors
wayland_titlebar_color #3f4451
macos_titlebar_color #3f4451

# Tab bar colors
active_tab_background #3f4451
active_tab_foreground #abb2bf
inactive_tab_background #474c59
inactive_tab_foreground #7a808e
tab_bar_background #474c59

# The 16 terminal colors
# normal
color0 #3f4451
color1 #e05561
color2 #8cc265
color3 #d18f52
color4 #4aa5f0
color5 #c162de
color6 #42b3c2
color7 #abb2bf

# bright
color8 #6c727f
color9 #e05561
color10 #8cc265
color11 #d18f52
color12 #4aa5f0
color13 #c162de
color14 #42b3c2
color15 #ffffff

# extended base16 colors
color16 #d8725a
color17 #a26257
color18 #474c59
color19 #4c515e
color20 #7a808e
color21 #bcc1cc
