# vim:ft=kitty

## name:     base16 Miami
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 Miami
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #000000
foreground #f7f1ff
selection_background #f7f1ff
selection_foreground #1e1d1f

# Cursor colors
cursor #f7f1ff
cursor_text_color #000000

# URL underline color when hovering with mouse
url_color #88858c

# Kitty window border colors
active_border_color #69676c
inactive_border_color #111112

# OS Window titlebar colors
wayland_titlebar_color #000000
macos_titlebar_color #000000

# Tab bar colors
active_tab_background #000000
active_tab_foreground #f7f1ff
inactive_tab_background #111112
inactive_tab_foreground #88858c
tab_bar_background #111112

# The 16 terminal colors
# normal
color0 #000000
color1 #ff4c8b
color2 #7fffd4
color3 #ffd84c
color4 #00ffa8
color5 #d36cff
color6 #47cfff
color7 #f7f1ff

# bright
color8 #69676c
color9 #ff4c8b
color10 #7fffd4
color11 #ffd84c
color12 #00ffa8
color13 #d36cff
color14 #47cfff
color15 #f7f1ff

# extended base16 colors
color16 #ff926c
color17 #a65f46
color18 #111112
color19 #1e1d1f
color20 #88858c
color21 #f9f4ff
