# vim:ft=kitty

## name:     base16 Serendipity Morning
## author:   Micheal Andreuzza (https://michaelandreuzza.com/)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Serendipity Serendipity Morning from the Serendipity theme family

# Scheme name: base16 Serendipity Morning
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #f6f7fb
foreground #3f4363
selection_background #3f4363
selection_foreground #eaebee

# Cursor colors
cursor #3f4363
cursor_text_color #f6f7fb

# URL underline color when hovering with mouse
url_color #505575

# Kitty window border colors
active_border_color #6d7296
inactive_border_color #eaebee

# OS Window titlebar colors
wayland_titlebar_color #f6f7fb
macos_titlebar_color #f6f7fb

# Tab bar colors
active_tab_background #f6f7fb
active_tab_foreground #3f4363
inactive_tab_background #eaebee
inactive_tab_foreground #505575
tab_bar_background #eaebee

# The 16 terminal colors
# normal
color0 #f6f7fb
color1 #c25a4d
color2 #2f7aab
color3 #785fd0
color4 #6288d8
color5 #785fd0
color6 #e58678
color7 #3f4363

# bright
color8 #6d7296
color9 #c25a4d
color10 #2f7aab
color11 #785fd0
color12 #6288d8
color13 #785fd0
color14 #e58678
color15 #f6f7fb

# extended base16 colors
color16 #c25a4d
color17 #2f7aab
color18 #eaebee
color19 #eaebee
color20 #505575
color21 #3f4363
