# vim:ft=kitty

## name:     base16 Paris
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 Paris
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #1a0a30
foreground #f7f1ff
selection_background #f7f1ff
selection_foreground #352649

# Cursor colors
cursor #f7f1ff
cursor_text_color #1a0a30

# URL underline color when hovering with mouse
url_color #9489a2

# Kitty window border colors
active_border_color #c4bdff
inactive_border_color #291a3e

# OS Window titlebar colors
wayland_titlebar_color #1a0a30
macos_titlebar_color #1a0a30

# Tab bar colors
active_tab_background #1a0a30
active_tab_foreground #f7f1ff
inactive_tab_background #291a3e
inactive_tab_foreground #9489a2
tab_bar_background #291a3e

# The 16 terminal colors
# normal
color0 #1a0a30
color1 #fc618d
color2 #7bd88f
color3 #fce566
color4 #a3f3ff
color5 #c4bdff
color6 #a3f3ff
color7 #f7f1ff

# bright
color8 #c4bdff
color9 #fc618d
color10 #7bd88f
color11 #fce566
color12 #a3f3ff
color13 #c4bdff
color14 #a3f3ff
color15 #f7f1ff

# extended base16 colors
color16 #fca37a
color17 #ad6d60
color18 #291a3e
color19 #352649
color20 #9489a2
color21 #f9f4ff
