# vim:ft=kitty

## name:     base16 Serendipity Midnight
## author:   Micheal Andreuzza (https://michaelandreuzza.com/)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Serendipity Serendipity Midnight from the Serendipity theme family

# Scheme name: base16 Serendipity Midnight
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #151726
foreground #dee0ef
selection_background #dee0ef
selection_foreground #1c1e2d

# Cursor colors
cursor #dee0ef
cursor_text_color #151726

# URL underline color when hovering with mouse
url_color #8d8f9e

# Kitty window border colors
active_border_color #6b6d7c
inactive_border_color #1c1e2d

# OS Window titlebar colors
wayland_titlebar_color #151726
macos_titlebar_color #151726

# Tab bar colors
active_tab_background #151726
active_tab_foreground #dee0ef
inactive_tab_background #1c1e2d
inactive_tab_foreground #8d8f9e
tab_bar_background #1c1e2d

# The 16 terminal colors
# normal
color0 #151726
color1 #ee8679
color2 #5ba2d0
color3 #a78bfa
color4 #94b8ff
color5 #a78bfa
color6 #f8d2c9
color7 #dee0ef

# bright
color8 #6b6d7c
color9 #ee8679
color10 #5ba2d0
color11 #a78bfa
color12 #94b8ff
color13 #a78bfa
color14 #f8d2c9
color15 #151726

# extended base16 colors
color16 #ee8679
color17 #5ba2d0
color18 #1c1e2d
color19 #1c1e2d
color20 #8d8f9e
color21 #dee0ef
