# vim:ft=kitty

## name:     base16 Praha
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 Praha
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #1a1a1a
foreground #ffffff
selection_background #ffffff
selection_foreground #353535

# Cursor colors
cursor #ffffff
cursor_text_color #1a1a1a

# URL underline color when hovering with mouse
url_color #989898

# Kitty window border colors
active_border_color #6272a4
inactive_border_color #2a2a2a

# OS Window titlebar colors
wayland_titlebar_color #1a1a1a
macos_titlebar_color #1a1a1a

# Tab bar colors
active_tab_background #1a1a1a
active_tab_foreground #ffffff
inactive_tab_background #2a2a2a
inactive_tab_foreground #989898
tab_bar_background #2a2a2a

# The 16 terminal colors
# normal
color0 #1a1a1a
color1 #ff5555
color2 #b8e6a0
color3 #ffe4a3
color4 #bd93f9
color5 #ff9aa2
color6 #8be9fd
color7 #ffffff

# bright
color8 #6272a4
color9 #ff5555
color10 #b8e6a0
color11 #ffe4a3
color12 #bd93f9
color13 #ff9aa2
color14 #8be9fd
color15 #ffffff

# extended base16 colors
color16 #ff9c7c
color17 #af6e5a
color18 #2a2a2a
color19 #353535
color20 #989898
color21 #ffffff
