# vim:ft=kitty

## name:     base16 Helsinki
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 Helsinki
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #f8fafe
foreground #544d40
selection_background #544d40
selection_foreground #e4e5e7

# Cursor colors
cursor #544d40
cursor_text_color #f8fafe

# URL underline color when hovering with mouse
url_color #8d8a82

# Kitty window border colors
active_border_color #b0a999
inactive_border_color #edeef1

# OS Window titlebar colors
wayland_titlebar_color #f8fafe
macos_titlebar_color #f8fafe

# Tab bar colors
active_tab_background #f8fafe
active_tab_foreground #544d40
inactive_tab_background #edeef1
inactive_tab_foreground #8d8a82
tab_bar_background #edeef1

# The 16 terminal colors
# normal
color0 #f8fafe
color1 #1faa9e
color2 #733d9a
color3 #2e70ad
color4 #b55a0f
color5 #3e9d21
color6 #bd4c3d
color7 #544d40

# bright
color8 #b0a999
color9 #1faa9e
color10 #733d9a
color11 #2e70ad
color12 #b55a0f
color13 #3e9d21
color14 #bd4c3d
color15 #000000

# extended base16 colors
color16 #268da6
color17 #1b6374
color18 #edeef1
color19 #e4e5e7
color20 #8d8a82
color21 #3b362d
