# vim:ft=kitty

## name:     base16 Sequoia Monochrome Dark
## author:   Micheal Andreuzza (https://michaelandreuzza.com/)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Sequoia Sequoia Monochrome Dark from the Sequoia theme family

# Scheme name: base16 Sequoia Monochrome Dark
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #0f1014
foreground #868690
selection_background #868690
selection_foreground #111216

# Cursor colors
cursor #868690
cursor_text_color #0f1014

# URL underline color when hovering with mouse
url_color #575861

# Kitty window border colors
active_border_color #43444d
inactive_border_color #111216

# OS Window titlebar colors
wayland_titlebar_color #0f1014
macos_titlebar_color #0f1014

# Tab bar colors
active_tab_background #0f1014
active_tab_foreground #868690
inactive_tab_background #111216
inactive_tab_foreground #575861
tab_bar_background #111216

# The 16 terminal colors
# normal
color0 #0f1014
color1 #999eb2
color2 #626983
color3 #d3d5de
color4 #7c829d
color5 #d3d5de
color6 #b6bac8
color7 #868690

# bright
color8 #43444d
color9 #999eb2
color10 #626983
color11 #d3d5de
color12 #7c829d
color13 #d3d5de
color14 #b6bac8
color15 #0f1014

# extended base16 colors
color16 #999eb2
color17 #626983
color18 #111216
color19 #111216
color20 #575861
color21 #868690
