# vim:ft=kitty

## name:     base24 Github Dark High Contrast
## author:   Tinted Theming (https://github.com/tinted-theming)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base24 Github Dark High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #0d1117
foreground #d1d7e0
selection_background #d1d7e0
selection_foreground #2f3742

# Cursor colors
cursor #d1d7e0
cursor_text_color #0d1117

# URL underline color when hovering with mouse
url_color #9198a1

# Kitty window border colors
active_border_color #656c76
inactive_border_color #151b23

# OS Window titlebar colors
wayland_titlebar_color #0d1117
macos_titlebar_color #0d1117

# Tab bar colors
active_tab_background #0d1117
active_tab_foreground #d1d7e0
inactive_tab_background #151b23
inactive_tab_foreground #9198a1
tab_bar_background #151b23

# The 16 terminal colors
# normal
color0 #0d1117
color1 #ff9492
color2 #28d751
color3 #f0b72f
color4 #71b7ff
color5 #cb9eff
color6 #39c5cf
color7 #d1d7e0

# bright
color8 #656c76
color9 #ffb1af
color10 #4ae168
color11 #f7c843
color12 #91cbff
color13 #dbb7ff
color14 #56d4dd
color15 #ffffff

# extended base16 colors
color16 #ffb757
color17 #ffb1af
color18 #151b23
color19 #2f3742
color20 #9198a1
color21 #f0f6fc
