# vim:ft=kitty

## name:     base24 Github Light High Contrast
## author:   Tinted Theming (https://github.com/tinted-theming)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base24 Github Light High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #ffffff
foreground #454c54
selection_background #454c54
selection_foreground #d1d9e0

# Cursor colors
cursor #454c54
cursor_text_color #ffffff

# URL underline color when hovering with mouse
url_color #59636e

# Kitty window border colors
active_border_color #818b98
inactive_border_color #f6f8fa

# OS Window titlebar colors
wayland_titlebar_color #ffffff
macos_titlebar_color #ffffff

# Tab bar colors
active_tab_background #ffffff
active_tab_foreground #454c54
inactive_tab_background #f6f8fa
inactive_tab_foreground #59636e
tab_bar_background #f6f8fa

# The 16 terminal colors
# normal
color0 #ffffff
color1 #a0111f
color2 #024c1a
color3 #603700
color4 #0349b4
color5 #622cbc
color6 #1b7c83
color7 #454c54

# bright
color8 #818b98
color9 #86061d
color10 #055d20
color11 #4e2c00
color12 #1168e3
color13 #844ae7
color14 #3192aa
color15 #010409

# extended base16 colors
color16 #702c00
color17 #86061d
color18 #f6f8fa
color19 #d1d9e0
color20 #59636e
color21 #25292e
