# vim:ft=kitty

## name:     base16 Sequoia Moonlight Light
## author:   Micheal Andreuzza (https://michaelandreuzza.com/)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Sequoia Sequoia Moonlight Light from the Sequoia theme family

# Scheme name: base16 Sequoia Moonlight Light
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #edeef2
foreground #282930
selection_background #282930
selection_foreground #e2e3e8

# Cursor colors
cursor #282930
cursor_text_color #edeef2

# URL underline color when hovering with mouse
url_color #42434e

# Kitty window border colors
active_border_color #565760
inactive_border_color #e2e3e8

# OS Window titlebar colors
wayland_titlebar_color #edeef2
macos_titlebar_color #edeef2

# Tab bar colors
active_tab_background #edeef2
active_tab_foreground #282930
inactive_tab_background #e2e3e8
inactive_tab_foreground #42434e
tab_bar_background #e2e3e8

# The 16 terminal colors
# normal
color0 #edeef2
color1 #c94da8
color2 #4a85d4
color3 #6a6a78
color4 #9a5fd9
color5 #6a6a78
color6 #d9884a
color7 #282930

# bright
color8 #565760
color9 #c94da8
color10 #4a85d4
color11 #6a6a78
color12 #9a5fd9
color13 #6a6a78
color14 #d9884a
color15 #0f1014

# extended base16 colors
color16 #c94da8
color17 #4a85d4
color18 #e2e3e8
color19 #e2e3e8
color20 #42434e
color21 #282930
