# vim:ft=kitty

## name:     base16 Serendipity Sunset
## author:   Micheal Andreuzza (https://michaelandreuzza.com/)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Serendipity Serendipity Sunset from the Serendipity theme family

# Scheme name: base16 Serendipity Sunset
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #202231
foreground #dee0ef
selection_background #dee0ef
selection_foreground #272938

# Cursor colors
cursor #dee0ef
cursor_text_color #202231

# URL underline color when hovering with mouse
url_color #6b6d7c

# Kitty window border colors
active_border_color #8d8f9e
inactive_border_color #272938

# OS Window titlebar colors
wayland_titlebar_color #202231
macos_titlebar_color #202231

# Tab bar colors
active_tab_background #202231
active_tab_foreground #dee0ef
inactive_tab_background #272938
inactive_tab_foreground #6b6d7c
tab_bar_background #272938

# The 16 terminal colors
# normal
color0 #202231
color1 #d1918f
color2 #709bbd
color3 #a392dc
color4 #a0b6e8
color5 #a392dc
color6 #d6b4b4
color7 #dee0ef

# bright
color8 #8d8f9e
color9 #d1918f
color10 #709bbd
color11 #a392dc
color12 #a0b6e8
color13 #a392dc
color14 #d6b4b4
color15 #202231

# extended base16 colors
color16 #d1918f
color17 #709bbd
color18 #272938
color19 #272938
color20 #6b6d7c
color21 #dee0ef
