# vim:ft=kitty

## name:     base16 Corduroy Dark
## author:   taysatte (https://github.com/taysatte)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    A deeper, higher-contrast Corduroy variant with vintage warmth and soft textures.

# Scheme name: base16 Corduroy Dark
# Scheme author: taysatte (https://github.com/taysatte)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #141016
foreground #ddd8df
selection_background #ddd8df
selection_foreground #221a26

# Cursor colors
cursor #ddd8df
cursor_text_color #141016

# URL underline color when hovering with mouse
url_color #9a8d9e

# Kitty window border colors
active_border_color #7d7082
inactive_border_color #1b151e

# OS Window titlebar colors
wayland_titlebar_color #141016
macos_titlebar_color #141016

# Tab bar colors
active_tab_background #141016
active_tab_foreground #ddd8df
inactive_tab_background #1b151e
inactive_tab_foreground #9a8d9e
tab_bar_background #1b151e

# The 16 terminal colors
# normal
color0 #141016
color1 #e8758a
color2 #55a0a0
color3 #f0bd9c
color4 #dc92a3
color5 #cf98c4
color6 #f0a89b
color7 #ddd8df

# bright
color8 #7d7082
color9 #e8758a
color10 #55a0a0
color11 #f0bd9c
color12 #dc92a3
color13 #cf98c4
color14 #f0a89b
color15 #5a5160

# extended base16 colors
color16 #f0a89b
color17 #9a8d9e
color18 #1b151e
color19 #221a26
color20 #9a8d9e
color21 #ddd8df
