# vim:ft=kitty

## name:     base16 Corduroy
## author:   taysatte (https://github.com/taysatte)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Embrace vintage warmth, soft textures, and a touch of retro flair.

# Scheme name: base16 Corduroy
# Scheme author: taysatte (https://github.com/taysatte)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #1d1920
foreground #cdc8d0
selection_background #cdc8d0
selection_foreground #2e2533

# Cursor colors
cursor #cdc8d0
cursor_text_color #1d1920

# URL underline color when hovering with mouse
url_color #887b8c

# Kitty window border colors
active_border_color #6f6373
inactive_border_color #261e2a

# OS Window titlebar colors
wayland_titlebar_color #1d1920
macos_titlebar_color #1d1920

# Tab bar colors
active_tab_background #1d1920
active_tab_foreground #cdc8d0
inactive_tab_background #261e2a
inactive_tab_foreground #887b8c
tab_bar_background #261e2a

# The 16 terminal colors
# normal
color0 #1d1920
color1 #e06278
color2 #4b8686
color3 #edb392
color4 #d27f91
color5 #c285b2
color6 #e99d90
color7 #cdc8d0

# bright
color8 #6f6373
color9 #e06278
color10 #4b8686
color11 #edb392
color12 #d27f91
color13 #c285b2
color14 #e99d90
color15 #504757

# extended base16 colors
color16 #e99d90
color17 #887b8c
color18 #261e2a
color19 #2e2533
color20 #887b8c
color21 #cdc8d0
