# vim:ft=kitty

## name:     base16 Bogota
## author:   xscriptor (https://github.com/xscriptor)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 Bogota
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #200b0a
foreground #f7f1ff
selection_background #f7f1ff
selection_foreground #3a2727

# Cursor colors
cursor #f7f1ff
cursor_text_color #200b0a

# URL underline color when hovering with mouse
url_color #968a91

# Kitty window border colors
active_border_color #525053
inactive_border_color #2f1b1b

# OS Window titlebar colors
wayland_titlebar_color #200b0a
macos_titlebar_color #200b0a

# Tab bar colors
active_tab_background #200b0a
active_tab_foreground #f7f1ff
inactive_tab_background #2f1b1b
inactive_tab_foreground #968a91
tab_bar_background #2f1b1b

# The 16 terminal colors
# normal
color0 #200b0a
color1 #fc618d
color2 #7bd88f
color3 #ffed89
color4 #47e6ff
color5 #ff9999
color6 #47e6ff
color7 #f7f1ff

# bright
color8 #525053
color9 #fc618d
color10 #7bd88f
color11 #ffed89
color12 #47e6ff
color13 #ff9999
color14 #47e6ff
color15 #f7f1ff

# extended base16 colors
color16 #fea78b
color17 #b0705e
color18 #2f1b1b
color19 #3a2727
color20 #968a91
color21 #f9f4ff
