# vim:ft=kitty

## name:     tinted8 Github Light Colorblind
## author:   Tinted Theming (https://github.com/tinted-theming)
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# The basic colors
background #ffffff
foreground #1f2328
selection_background #1f2328
selection_foreground #1f2328

# Cursor colors
cursor #1f2328
cursor_text_color #ffffff

# URL underline color when hovering with mouse
url_color #59636e

# Kitty window border colors
active_border_color #3d454c
inactive_border_color #

# OS Window titlebar colors
wayland_titlebar_color #ffffff
macos_titlebar_color #ffffff

# Tab bar colors
active_tab_background #ffffff
active_tab_foreground #1f2328
inactive_tab_background #
inactive_tab_foreground #59636e
tab_bar_background #

# The 16 terminal colors
# normal
color0 #1f2328
color1 #bc4c00
color2 #0550ae
color3 #4d2d00
color4 #0969da
color5 #8250df
color6 #1b7c83
color7 #59636e

# bright
color8 #393f46
color9 #953800
color10 #0969da
color11 #633c01
color12 #218bff
color13 #a475f9
color14 #3192aa
color15 #818b98
