# vim:ft=kitty

## name:     tinted8 Github Dark High Contrast
## author:   Tinted Theming (https://github.com/tinted-theming)
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# The basic colors
background #010409
foreground #ffffff
selection_background #f0f6fc
selection_foreground #f0f6fc

# Cursor colors
cursor #ffffff
cursor_text_color #010409

# URL underline color when hovering with mouse
url_color #656c76

# Kitty window border colors
active_border_color #484e55
inactive_border_color #

# OS Window titlebar colors
wayland_titlebar_color #010409
macos_titlebar_color #010409

# Tab bar colors
active_tab_background #010409
active_tab_foreground #ffffff
inactive_tab_background #
inactive_tab_foreground #656c76
tab_bar_background #

# The 16 terminal colors
# normal
color0 #2f3742
color1 #ff9492
color2 #28d751
color3 #f0b72f
color4 #71b7ff
color5 #cb9eff
color6 #39c5cf
color7 #f0f6fc

# bright
color8 #656c76
color9 #ffb1af
color10 #4ae168
color11 #f7c843
color12 #91cbff
color13 #dbb7ff
color14 #56d4dd
color15 #ffffff
